//
// ActivateAddOn200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ActivateAddOn200Response: Sendable, Codable, Hashable {

    public var id: UUID
    public var addOn: String
    public var status: String
    public var message: String

    public init(id: UUID, addOn: String, status: String, message: String) {
        self.id = id
        self.addOn = addOn
        self.status = status
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case addOn = "add_on"
        case status
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(addOn, forKey: .addOn)
        try container.encode(status, forKey: .status)
        try container.encode(message, forKey: .message)
    }
}


extension ActivateAddOn200Response: Identifiable {}
