//
// AddContactListMemberRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddContactListMemberRequest: Sendable, Codable, Hashable {

    public var contactId: UUID

    public init(contactId: UUID) {
        self.contactId = contactId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contactId = "contact_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contactId, forKey: .contactId)
    }
}

