//
// AddOn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddOn: Sendable, Codable, Hashable {

    public var name: String
    public var displayName: String
    public var description: String
    public var priceNaira: Int
    public var pricingModel: String
    public var active: Bool

    public init(name: String, displayName: String, description: String, priceNaira: Int, pricingModel: String, active: Bool) {
        self.name = name
        self.displayName = displayName
        self.description = description
        self.priceNaira = priceNaira
        self.pricingModel = pricingModel
        self.active = active
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case displayName = "display_name"
        case description
        case priceNaira = "price_naira"
        case pricingModel = "pricing_model"
        case active
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(description, forKey: .description)
        try container.encode(priceNaira, forKey: .priceNaira)
        try container.encode(pricingModel, forKey: .pricingModel)
        try container.encode(active, forKey: .active)
    }
}

