//
// AddSharedMemberRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddSharedMemberRequest: Sendable, Codable, Hashable {

    public enum Role: String, Sendable, Codable, CaseIterable {
        case manager = "manager"
        case member = "member"
    }
    public var memberEmail: String
    public var role: Role? = .member

    public init(memberEmail: String, role: Role? = .member) {
        self.memberEmail = memberEmail
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case memberEmail = "member_email"
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(memberEmail, forKey: .memberEmail)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

