//
// AdminFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AdminFull: Sendable, Codable, Hashable {

    public enum Role: String, Sendable, Codable, CaseIterable {
        case admin = "admin"
        case viewer = "viewer"
    }
    public var id: UUID
    public var tenantId: UUID
    public var email: String
    public var displayName: String?
    public var role: Role
    public var lastLoginAt: Date?
    public var createdAt: Date
    public var disabled: Bool
    public var disabledAt: Date?
    /** Present ONLY on POST response when lockally generated the password. Shown once. */
    public var password: String?

    public init(id: UUID, tenantId: UUID, email: String, displayName: String? = nil, role: Role, lastLoginAt: Date? = nil, createdAt: Date, disabled: Bool, disabledAt: Date? = nil, password: String? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.email = email
        self.displayName = displayName
        self.role = role
        self.lastLoginAt = lastLoginAt
        self.createdAt = createdAt
        self.disabled = disabled
        self.disabledAt = disabledAt
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case email
        case displayName = "display_name"
        case role
        case lastLoginAt = "last_login_at"
        case createdAt = "created_at"
        case disabled
        case disabledAt = "disabled_at"
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encode(role, forKey: .role)
        try container.encodeIfPresent(lastLoginAt, forKey: .lastLoginAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(disabled, forKey: .disabled)
        try container.encodeIfPresent(disabledAt, forKey: .disabledAt)
        try container.encodeIfPresent(password, forKey: .password)
    }
}


extension AdminFull: Identifiable {}
