//
// Alias.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Alias: Sendable, Codable, Hashable {

    public var id: UUID
    public var tenantId: UUID
    public var aliasAddress: String
    public var aliasTarget: String
    public var createdAt: Date

    public init(id: UUID, tenantId: UUID, aliasAddress: String, aliasTarget: String, createdAt: Date) {
        self.id = id
        self.tenantId = tenantId
        self.aliasAddress = aliasAddress
        self.aliasTarget = aliasTarget
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case aliasAddress = "alias_address"
        case aliasTarget = "alias_target"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(aliasAddress, forKey: .aliasAddress)
        try container.encode(aliasTarget, forKey: .aliasTarget)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension Alias: Identifiable {}
