//
// AuditEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuditEvent: Sendable, Codable, Hashable {

    public var email: String?
    public var eventType: String?
    public var detail: String?
    public var ip: String?
    public var time: Date?

    public init(email: String? = nil, eventType: String? = nil, detail: String? = nil, ip: String? = nil, time: Date? = nil) {
        self.email = email
        self.eventType = eventType
        self.detail = detail
        self.ip = ip
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case eventType = "event_type"
        case detail
        case ip
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(eventType, forKey: .eventType)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(ip, forKey: .ip)
        try container.encodeIfPresent(time, forKey: .time)
    }
}

