//
// BatchLookupPublicKeys200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BatchLookupPublicKeys200ResponseDataInner: Sendable, Codable, Hashable {

    public var email: String?
    public var publicKey: String?
    public var keyId: UUID?

    public init(email: String? = nil, publicKey: String? = nil, keyId: UUID? = nil) {
        self.email = email
        self.publicKey = publicKey
        self.keyId = keyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case publicKey = "public_key"
        case keyId = "key_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(publicKey, forKey: .publicKey)
        try container.encodeIfPresent(keyId, forKey: .keyId)
    }
}

