//
// BatchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BatchResult: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "queued"
        case scheduled = "scheduled"
        case suppressed = "suppressed"
    }
    public var index: Int?
    public var id: UUID?
    public var messageId: String?
    public var status: Status?
    /** Present when this message failed; the others are then absent. */
    public var error: String?

    public init(index: Int? = nil, id: UUID? = nil, messageId: String? = nil, status: Status? = nil, error: String? = nil) {
        self.index = index
        self.id = id
        self.messageId = messageId
        self.status = status
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case id
        case messageId = "message_id"
        case status
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(index, forKey: .index)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(messageId, forKey: .messageId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(error, forKey: .error)
    }
}


extension BatchResult: Identifiable {}
