//
// CalendarMember.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CalendarMember: Sendable, Codable, Hashable {

    public enum Role: String, Sendable, Codable, CaseIterable {
        case viewer = "viewer"
        case editor = "editor"
        case owner = "owner"
    }
    public var id: UUID
    public var calendarId: UUID
    public var tenantId: UUID
    public var userEmail: String
    public var role: Role
    public var createdAt: Date

    public init(id: UUID, calendarId: UUID, tenantId: UUID, userEmail: String, role: Role, createdAt: Date) {
        self.id = id
        self.calendarId = calendarId
        self.tenantId = tenantId
        self.userEmail = userEmail
        self.role = role
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case calendarId = "calendar_id"
        case tenantId = "tenant_id"
        case userEmail = "user_email"
        case role
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(calendarId, forKey: .calendarId)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(userEmail, forKey: .userEmail)
        try container.encode(role, forKey: .role)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension CalendarMember: Identifiable {}
