//
// CalendarIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CalendarIntegration: Sendable, Codable, Hashable {

    public enum Provider: String, Sendable, Codable, CaseIterable {
        case exchange = "exchange"
        case googleCalendar = "google_calendar"
        case teams = "teams"
        case zoom = "zoom"
        case erp = "erp"
    }
    public enum Status: String, Sendable, Codable, CaseIterable {
        case connected = "connected"
        case disconnected = "disconnected"
        case error = "error"
        case syncing = "syncing"
    }
    public var id: UUID
    public var tenantId: UUID
    public var provider: Provider
    public var label: String?
    public var status: Status
    public var lastSyncAt: Date?
    public var errorMessage: String?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, tenantId: UUID, provider: Provider, label: String? = nil, status: Status, lastSyncAt: Date? = nil, errorMessage: String? = nil, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.tenantId = tenantId
        self.provider = provider
        self.label = label
        self.status = status
        self.lastSyncAt = lastSyncAt
        self.errorMessage = errorMessage
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case provider
        case label
        case status
        case lastSyncAt = "last_sync_at"
        case errorMessage = "error_message"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(lastSyncAt, forKey: .lastSyncAt)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension CalendarIntegration: Identifiable {}
