//
// CalendarEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CalendarEvent: Sendable, Codable, Hashable {

    public var id: UUID
    public var calendarId: UUID
    public var tenantId: UUID
    public var uid: String
    public var title: String
    public var description: String?
    public var location: String?
    public var startsAt: Date
    public var endsAt: Date
    public var allDay: Bool
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, calendarId: UUID, tenantId: UUID, uid: String, title: String, description: String? = nil, location: String? = nil, startsAt: Date, endsAt: Date, allDay: Bool, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.calendarId = calendarId
        self.tenantId = tenantId
        self.uid = uid
        self.title = title
        self.description = description
        self.location = location
        self.startsAt = startsAt
        self.endsAt = endsAt
        self.allDay = allDay
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case calendarId = "calendar_id"
        case tenantId = "tenant_id"
        case uid
        case title
        case description
        case location
        case startsAt = "starts_at"
        case endsAt = "ends_at"
        case allDay = "all_day"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(calendarId, forKey: .calendarId)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(uid, forKey: .uid)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encode(startsAt, forKey: .startsAt)
        try container.encode(endsAt, forKey: .endsAt)
        try container.encode(allDay, forKey: .allDay)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension CalendarEvent: Identifiable {}
