//
// Contact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Contact: Sendable, Codable, Hashable {

    public enum ContactType: String, Sendable, Codable, CaseIterable {
        case _internal = "internal"
        case external = "external"
    }
    public var id: UUID
    public var tenantId: UUID
    public var name: String
    public var email: String
    public var phone: String?
    public var company: String?
    public var notes: String?
    public var contactType: ContactType
    public var source: String?
    public var department: String?
    public var role: String?
    public var status: String
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, tenantId: UUID, name: String, email: String, phone: String? = nil, company: String? = nil, notes: String? = nil, contactType: ContactType, source: String? = nil, department: String? = nil, role: String? = nil, status: String, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.tenantId = tenantId
        self.name = name
        self.email = email
        self.phone = phone
        self.company = company
        self.notes = notes
        self.contactType = contactType
        self.source = source
        self.department = department
        self.role = role
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case name
        case email
        case phone
        case company
        case notes
        case contactType = "contact_type"
        case source
        case department
        case role
        case status
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(name, forKey: .name)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encode(contactType, forKey: .contactType)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encode(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension Contact: Identifiable {}
