//
// ContactList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ContactList: Sendable, Codable, Hashable {

    public enum Visibility: String, Sendable, Codable, CaseIterable {
        case companyWide = "company_wide"
        case restricted = "restricted"
    }
    public var id: UUID
    public var tenantId: UUID
    public var name: String
    public var description: String?
    public var visibility: Visibility
    public var memberCount: Int
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, tenantId: UUID, name: String, description: String? = nil, visibility: Visibility, memberCount: Int, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.tenantId = tenantId
        self.name = name
        self.description = description
        self.visibility = visibility
        self.memberCount = memberCount
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case name
        case description
        case visibility
        case memberCount = "member_count"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(visibility, forKey: .visibility)
        try container.encode(memberCount, forKey: .memberCount)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension ContactList: Identifiable {}
