//
// CreateBillingCheckout200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateBillingCheckout200Response: Sendable, Codable, Hashable {

    public var authorizationUrl: String
    public var reference: String

    public init(authorizationUrl: String, reference: String) {
        self.authorizationUrl = authorizationUrl
        self.reference = reference
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case authorizationUrl = "authorization_url"
        case reference
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(authorizationUrl, forKey: .authorizationUrl)
        try container.encode(reference, forKey: .reference)
    }
}

