//
// CreateContactRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateContactRequest: Sendable, Codable, Hashable {

    public enum ContactType: String, Sendable, Codable, CaseIterable {
        case _internal = "internal"
        case external = "external"
    }
    public var name: String
    public var email: String
    public var phone: String?
    public var company: String?
    public var notes: String?
    public var contactType: ContactType? = .external
    public var department: String?
    public var role: String?

    public init(name: String, email: String, phone: String? = nil, company: String? = nil, notes: String? = nil, contactType: ContactType? = .external, department: String? = nil, role: String? = nil) {
        self.name = name
        self.email = email
        self.phone = phone
        self.company = company
        self.notes = notes
        self.contactType = contactType
        self.department = department
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case email
        case phone
        case company
        case notes
        case contactType = "contact_type"
        case department
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(contactType, forKey: .contactType)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

