//
// CreateMigrationCredentialRequestCredentials.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateMigrationCredentialRequestCredentials: Sendable, Codable, Hashable {

    public var host: String
    public var port: Int
    public var username: String?
    public var password: String?
    public var oauthToken: String?

    public init(host: String, port: Int, username: String? = nil, password: String? = nil, oauthToken: String? = nil) {
        self.host = host
        self.port = port
        self.username = username
        self.password = password
        self.oauthToken = oauthToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case host
        case port
        case username
        case password
        case oauthToken = "oauth_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(host, forKey: .host)
        try container.encode(port, forKey: .port)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(oauthToken, forKey: .oauthToken)
    }
}

