//
// CreateUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateUserRequest: Sendable, Codable, Hashable {

    public var email: String
    public var firstName: String
    public var lastName: String
    public var title: String?
    public var department: String?

    public init(email: String, firstName: String, lastName: String, title: String? = nil, department: String? = nil) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.title = title
        self.department = department
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case firstName = "first_name"
        case lastName = "last_name"
        case title
        case department
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(department, forKey: .department)
    }
}

