//
// CreateMigrationCredentialRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateMigrationCredentialRequest: Sendable, Codable, Hashable {

    public enum Provider: String, Sendable, Codable, CaseIterable {
        case imap = "imap"
        case google = "google"
        case microsoft = "microsoft"
        case generic = "generic"
    }
    public var provider: Provider
    public var label: String?
    public var credentials: CreateMigrationCredentialRequestCredentials

    public init(provider: Provider, label: String? = nil, credentials: CreateMigrationCredentialRequestCredentials) {
        self.provider = provider
        self.label = label
        self.credentials = credentials
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case label
        case credentials
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(credentials, forKey: .credentials)
    }
}

