//
// CreateResourceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateResourceRequest: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case meetingRoom = "meeting_room"
        case equipment = "equipment"
    }
    public static let capacityRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var name: String
    public var type: ModelType? = .meetingRoom
    public var capacity: Int?

    public init(name: String, type: ModelType? = .meetingRoom, capacity: Int? = nil) {
        self.name = name
        self.type = type
        self.capacity = capacity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case capacity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(capacity, forKey: .capacity)
    }
}

