//
// CreateBillingCheckoutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateBillingCheckoutRequest: Sendable, Codable, Hashable {

    public enum Plan: String, Sendable, Codable, CaseIterable {
        case free = "free"
        case founder = "founder"
        case starter = "starter"
        case pro = "pro"
        case scale = "scale"
    }
    public var plan: Plan

    public init(plan: Plan) {
        self.plan = plan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case plan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(plan, forKey: .plan)
    }
}

