//
// CreateDedicatedIPRequestRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateDedicatedIPRequestRequest: Sendable, Codable, Hashable {

    public var note: String

    public init(note: String) {
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(note, forKey: .note)
    }
}

