//
// CreateUnitsCheckoutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateUnitsCheckoutRequest: Sendable, Codable, Hashable {

    public enum Bundle: String, Sendable, Codable, CaseIterable {
        case _1k = "1k"
        case _10k = "10k"
        case _50k = "50k"
        case _100k = "100k"
        case _1pkt = "1pkt"
        case _5pkt = "5pkt"
        case _10pkt = "10pkt"
        case _20pkt = "20pkt"
    }
    public var bundle: Bundle

    public init(bundle: Bundle) {
        self.bundle = bundle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bundle
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bundle, forKey: .bundle)
    }
}

