//
// CreateEncryptionKey201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateEncryptionKey201Response: Sendable, Codable, Hashable {

    public var id: UUID?
    public var mailboxId: UUID?
    public var createdAt: Date?

    public init(id: UUID? = nil, mailboxId: UUID? = nil, createdAt: Date? = nil) {
        self.id = id
        self.mailboxId = mailboxId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case mailboxId = "mailbox_id"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(mailboxId, forKey: .mailboxId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


extension CreateEncryptionKey201Response: Identifiable {}
