//
// CreateEncryptionRecoveryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateEncryptionRecoveryRequest: Sendable, Codable, Hashable {

    public var mailboxEmail: String
    public var recoveryBlob: String

    public init(mailboxEmail: String, recoveryBlob: String) {
        self.mailboxEmail = mailboxEmail
        self.recoveryBlob = recoveryBlob
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mailboxEmail = "mailbox_email"
        case recoveryBlob = "recovery_blob"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mailboxEmail, forKey: .mailboxEmail)
        try container.encode(recoveryBlob, forKey: .recoveryBlob)
    }
}

