//
// DedicatedIPRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DedicatedIPRequest: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case pending = "pending"
        case approved = "approved"
        case rejected = "rejected"
    }
    public var id: UUID
    public var tenantId: UUID
    public var status: Status
    public var note: String?
    public var adminNote: String?
    public var createdAt: Date
    public var resolvedAt: Date?

    public init(id: UUID, tenantId: UUID, status: Status, note: String? = nil, adminNote: String? = nil, createdAt: Date, resolvedAt: Date? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.status = status
        self.note = note
        self.adminNote = adminNote
        self.createdAt = createdAt
        self.resolvedAt = resolvedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case status
        case note
        case adminNote = "admin_note"
        case createdAt = "created_at"
        case resolvedAt = "resolved_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(adminNote, forKey: .adminNote)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(resolvedAt, forKey: .resolvedAt)
    }
}


extension DedicatedIPRequest: Identifiable {}
