//
// DirectoryPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DirectoryPermissions: Sendable, Codable, Hashable {

    public enum ContactViewAccess: String, Sendable, Codable, CaseIterable {
        case allUsers = "all_users"
        case sameDepartment = "same_department"
        case adminsOnly = "admins_only"
    }
    public enum ContactEditAccess: String, Sendable, Codable, CaseIterable {
        case allUsers = "all_users"
        case adminsOnly = "admins_only"
    }
    public enum ListManageAccess: String, Sendable, Codable, CaseIterable {
        case allUsers = "all_users"
        case listOwners = "list_owners"
        case adminsOnly = "admins_only"
    }
    public enum ExternalSharing: String, Sendable, Codable, CaseIterable {
        case allowed = "allowed"
        case restricted = "restricted"
        case disabled = "disabled"
    }
    public var tenantId: UUID
    public var contactViewAccess: ContactViewAccess
    public var contactEditAccess: ContactEditAccess
    public var listManageAccess: ListManageAccess
    public var externalSharing: ExternalSharing
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(tenantId: UUID, contactViewAccess: ContactViewAccess, contactEditAccess: ContactEditAccess, listManageAccess: ListManageAccess, externalSharing: ExternalSharing, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.tenantId = tenantId
        self.contactViewAccess = contactViewAccess
        self.contactEditAccess = contactEditAccess
        self.listManageAccess = listManageAccess
        self.externalSharing = externalSharing
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tenantId = "tenant_id"
        case contactViewAccess = "contact_view_access"
        case contactEditAccess = "contact_edit_access"
        case listManageAccess = "list_manage_access"
        case externalSharing = "external_sharing"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(contactViewAccess, forKey: .contactViewAccess)
        try container.encode(contactEditAccess, forKey: .contactEditAccess)
        try container.encode(listManageAccess, forKey: .listManageAccess)
        try container.encode(externalSharing, forKey: .externalSharing)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

