//
// DistributionListDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DistributionListDetail: Sendable, Codable, Hashable {

    public var id: UUID
    public var tenantId: UUID
    public var listAddress: String
    public var name: String?
    public var createdAt: Date
    public var members: [String]
    public var memberCount: Int

    public init(id: UUID, tenantId: UUID, listAddress: String, name: String? = nil, createdAt: Date, members: [String], memberCount: Int) {
        self.id = id
        self.tenantId = tenantId
        self.listAddress = listAddress
        self.name = name
        self.createdAt = createdAt
        self.members = members
        self.memberCount = memberCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case listAddress = "list_address"
        case name
        case createdAt = "created_at"
        case members
        case memberCount = "member_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(listAddress, forKey: .listAddress)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(members, forKey: .members)
        try container.encode(memberCount, forKey: .memberCount)
    }
}


extension DistributionListDetail: Identifiable {}
