//
// DNSRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DNSRecord: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case txt = "TXT"
        case mx = "MX"
    }
    public enum Purpose: String, Sendable, Codable, CaseIterable {
        case verification = "verification"
        case spf = "spf"
        case dkim = "dkim"
        case mxPrimary = "mx-primary"
        case mxBackup = "mx-backup"
        case dmarc = "dmarc"
    }
    public var type: ModelType
    public var name: String
    public var value: String
    public var ttl: Int
    /** MX records only. */
    public var priority: Int?
    public var purpose: Purpose

    public init(type: ModelType, name: String, value: String, ttl: Int, priority: Int? = nil, purpose: Purpose) {
        self.type = type
        self.name = name
        self.value = value
        self.ttl = ttl
        self.priority = priority
        self.purpose = purpose
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case name
        case value
        case ttl
        case priority
        case purpose
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(name, forKey: .name)
        try container.encode(value, forKey: .value)
        try container.encode(ttl, forKey: .ttl)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encode(purpose, forKey: .purpose)
    }
}

