//
// Domain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Domain: Sendable, Codable, Hashable {

    public var id: UUID
    public var tenantId: UUID
    public var domain: String
    public var verificationToken: String
    public var verified: Bool
    public var verifiedAt: Date?
    public var dkimSelector: String
    public var dkimPublicRecord: String
    public var createdAt: Date
    /** DNS records the tenant must publish under their own DNS. */
    public var records: [DNSRecord]?

    public init(id: UUID, tenantId: UUID, domain: String, verificationToken: String, verified: Bool, verifiedAt: Date? = nil, dkimSelector: String, dkimPublicRecord: String, createdAt: Date, records: [DNSRecord]? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.domain = domain
        self.verificationToken = verificationToken
        self.verified = verified
        self.verifiedAt = verifiedAt
        self.dkimSelector = dkimSelector
        self.dkimPublicRecord = dkimPublicRecord
        self.createdAt = createdAt
        self.records = records
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case domain
        case verificationToken = "verification_token"
        case verified
        case verifiedAt = "verified_at"
        case dkimSelector = "dkim_selector"
        case dkimPublicRecord = "dkim_public_record"
        case createdAt = "created_at"
        case records
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(domain, forKey: .domain)
        try container.encode(verificationToken, forKey: .verificationToken)
        try container.encode(verified, forKey: .verified)
        try container.encodeIfPresent(verifiedAt, forKey: .verifiedAt)
        try container.encode(dkimSelector, forKey: .dkimSelector)
        try container.encode(dkimPublicRecord, forKey: .dkimPublicRecord)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(records, forKey: .records)
    }
}


extension Domain: Identifiable {}
