//
// GetAuditSummary200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAuditSummary200Response: Sendable, Codable, Hashable {

    public var adminActionsToday: Int?
    public var recentLogins: [AuditEvent]?
    public var recentExports: [AuditEvent]?
    public var deletedMailboxes: [AuditEvent]?
    public var generatedAt: Date?

    public init(adminActionsToday: Int? = nil, recentLogins: [AuditEvent]? = nil, recentExports: [AuditEvent]? = nil, deletedMailboxes: [AuditEvent]? = nil, generatedAt: Date? = nil) {
        self.adminActionsToday = adminActionsToday
        self.recentLogins = recentLogins
        self.recentExports = recentExports
        self.deletedMailboxes = deletedMailboxes
        self.generatedAt = generatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case adminActionsToday = "admin_actions_today"
        case recentLogins = "recent_logins"
        case recentExports = "recent_exports"
        case deletedMailboxes = "deleted_mailboxes"
        case generatedAt = "generated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(adminActionsToday, forKey: .adminActionsToday)
        try container.encodeIfPresent(recentLogins, forKey: .recentLogins)
        try container.encodeIfPresent(recentExports, forKey: .recentExports)
        try container.encodeIfPresent(deletedMailboxes, forKey: .deletedMailboxes)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
    }
}

