//
// GetCalendarSecurity200ResponseDelegatedAccessInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCalendarSecurity200ResponseDelegatedAccessInner: Sendable, Codable, Hashable {

    public var calendarId: UUID?
    public var calendarName: String?
    public var userEmail: String?
    public var role: String?
    public var grantedAt: Date?

    public init(calendarId: UUID? = nil, calendarName: String? = nil, userEmail: String? = nil, role: String? = nil, grantedAt: Date? = nil) {
        self.calendarId = calendarId
        self.calendarName = calendarName
        self.userEmail = userEmail
        self.role = role
        self.grantedAt = grantedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case calendarId = "calendar_id"
        case calendarName = "calendar_name"
        case userEmail = "user_email"
        case role
        case grantedAt = "granted_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(calendarId, forKey: .calendarId)
        try container.encodeIfPresent(calendarName, forKey: .calendarName)
        try container.encodeIfPresent(userEmail, forKey: .userEmail)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(grantedAt, forKey: .grantedAt)
    }
}

