//
// GetCalendarSecurity200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCalendarSecurity200Response: Sendable, Codable, Hashable {

    public var totalCalendars: Int?
    public var publicCalendars: Int?
    public var privateCalendars: Int?
    public var totalMembers: Int?
    public var delegatedAccess: [GetCalendarSecurity200ResponseDelegatedAccessInner]?
    public var publicCalendarList: [GetCalendarSecurity200ResponsePublicCalendarListInner]?
    public var alerts: [GetCalendarSecurity200ResponseAlertsInner]?
    public var externalSharing: GetCalendarSecurity200ResponseExternalSharing?

    public init(totalCalendars: Int? = nil, publicCalendars: Int? = nil, privateCalendars: Int? = nil, totalMembers: Int? = nil, delegatedAccess: [GetCalendarSecurity200ResponseDelegatedAccessInner]? = nil, publicCalendarList: [GetCalendarSecurity200ResponsePublicCalendarListInner]? = nil, alerts: [GetCalendarSecurity200ResponseAlertsInner]? = nil, externalSharing: GetCalendarSecurity200ResponseExternalSharing? = nil) {
        self.totalCalendars = totalCalendars
        self.publicCalendars = publicCalendars
        self.privateCalendars = privateCalendars
        self.totalMembers = totalMembers
        self.delegatedAccess = delegatedAccess
        self.publicCalendarList = publicCalendarList
        self.alerts = alerts
        self.externalSharing = externalSharing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCalendars = "total_calendars"
        case publicCalendars = "public_calendars"
        case privateCalendars = "private_calendars"
        case totalMembers = "total_members"
        case delegatedAccess = "delegated_access"
        case publicCalendarList = "public_calendar_list"
        case alerts
        case externalSharing = "external_sharing"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalCalendars, forKey: .totalCalendars)
        try container.encodeIfPresent(publicCalendars, forKey: .publicCalendars)
        try container.encodeIfPresent(privateCalendars, forKey: .privateCalendars)
        try container.encodeIfPresent(totalMembers, forKey: .totalMembers)
        try container.encodeIfPresent(delegatedAccess, forKey: .delegatedAccess)
        try container.encodeIfPresent(publicCalendarList, forKey: .publicCalendarList)
        try container.encodeIfPresent(alerts, forKey: .alerts)
        try container.encodeIfPresent(externalSharing, forKey: .externalSharing)
    }
}

