//
// GetCalendarSecurity200ResponsePublicCalendarListInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCalendarSecurity200ResponsePublicCalendarListInner: Sendable, Codable, Hashable {

    public var id: UUID?
    public var name: String?
    public var ownerEmail: String?
    public var memberCount: Int?
    public var hasFeed: Bool?

    public init(id: UUID? = nil, name: String? = nil, ownerEmail: String? = nil, memberCount: Int? = nil, hasFeed: Bool? = nil) {
        self.id = id
        self.name = name
        self.ownerEmail = ownerEmail
        self.memberCount = memberCount
        self.hasFeed = hasFeed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case ownerEmail = "owner_email"
        case memberCount = "member_count"
        case hasFeed = "has_feed"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(ownerEmail, forKey: .ownerEmail)
        try container.encodeIfPresent(memberCount, forKey: .memberCount)
        try container.encodeIfPresent(hasFeed, forKey: .hasFeed)
    }
}


extension GetCalendarSecurity200ResponsePublicCalendarListInner: Identifiable {}
