//
// GetCalendarSecurity200ResponseExternalSharing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCalendarSecurity200ResponseExternalSharing: Sendable, Codable, Hashable {

    public var invitesAllowed: Bool?
    public var sharingAllowed: Bool?
    public var publicLinks: Bool?

    public init(invitesAllowed: Bool? = nil, sharingAllowed: Bool? = nil, publicLinks: Bool? = nil) {
        self.invitesAllowed = invitesAllowed
        self.sharingAllowed = sharingAllowed
        self.publicLinks = publicLinks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invitesAllowed = "invites_allowed"
        case sharingAllowed = "sharing_allowed"
        case publicLinks = "public_links"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(invitesAllowed, forKey: .invitesAllowed)
        try container.encodeIfPresent(sharingAllowed, forKey: .sharingAllowed)
        try container.encodeIfPresent(publicLinks, forKey: .publicLinks)
    }
}

