//
// GetCalendarSecurity200ResponseAlertsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCalendarSecurity200ResponseAlertsInner: Sendable, Codable, Hashable {

    public enum Level: String, Sendable, Codable, CaseIterable {
        case critical = "critical"
        case warning = "warning"
    }
    public var level: Level?
    public var message: String?

    public init(level: Level? = nil, message: String? = nil) {
        self.level = level
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case level
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(level, forKey: .level)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

