//
// GetDomainsStatus200ResponseDomainsInnerChecksInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDomainsStatus200ResponseDomainsInnerChecksInner: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case healthy = "healthy"
        case warning = "warning"
        case critical = "critical"
    }
    public var key: String?
    public var label: String?
    public var status: Status?

    public init(key: String? = nil, label: String? = nil, status: Status? = nil) {
        self.key = key
        self.label = label
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case label
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

