//
// GetDirectoryStats200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDirectoryStats200Response: Sendable, Codable, Hashable {

    public var totalContacts: Int?
    public var internalUsers: Int?
    public var externalContacts: Int?
    public var syncedContacts: Int?
    public var sharedLists: Int?
    public var directoryGroups: Int?

    public init(totalContacts: Int? = nil, internalUsers: Int? = nil, externalContacts: Int? = nil, syncedContacts: Int? = nil, sharedLists: Int? = nil, directoryGroups: Int? = nil) {
        self.totalContacts = totalContacts
        self.internalUsers = internalUsers
        self.externalContacts = externalContacts
        self.syncedContacts = syncedContacts
        self.sharedLists = sharedLists
        self.directoryGroups = directoryGroups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalContacts = "total_contacts"
        case internalUsers = "internal_users"
        case externalContacts = "external_contacts"
        case syncedContacts = "synced_contacts"
        case sharedLists = "shared_lists"
        case directoryGroups = "directory_groups"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalContacts, forKey: .totalContacts)
        try container.encodeIfPresent(internalUsers, forKey: .internalUsers)
        try container.encodeIfPresent(externalContacts, forKey: .externalContacts)
        try container.encodeIfPresent(syncedContacts, forKey: .syncedContacts)
        try container.encodeIfPresent(sharedLists, forKey: .sharedLists)
        try container.encodeIfPresent(directoryGroups, forKey: .directoryGroups)
    }
}

