//
// GetDirectoryActivity200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDirectoryActivity200ResponseDataInner: Sendable, Codable, Hashable {

    public var type: String?
    public var message: String?
    public var detail: String?
    public var timestamp: Date?

    public init(type: String? = nil, message: String? = nil, detail: String? = nil, timestamp: Date? = nil) {
        self.type = type
        self.message = message
        self.detail = detail
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case message
        case detail
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
    }
}

