//
// GetDomainsStatus200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDomainsStatus200Response: Sendable, Codable, Hashable {

    public var domains: [GetDomainsStatus200ResponseDomainsInner]?
    public var generatedAt: Date?

    public init(domains: [GetDomainsStatus200ResponseDomainsInner]? = nil, generatedAt: Date? = nil) {
        self.domains = domains
        self.generatedAt = generatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domains
        case generatedAt = "generated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(domains, forKey: .domains)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
    }
}

