//
// GetEncryptionKey200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetEncryptionKey200Response: Sendable, Codable, Hashable {

    public var id: UUID?
    public var email: String?
    public var publicKey: String?
    public var encryptedPrivateKey: String?
    public var kdfParams: JSONValue?
    public var version: Int?

    public init(id: UUID? = nil, email: String? = nil, publicKey: String? = nil, encryptedPrivateKey: String? = nil, kdfParams: JSONValue? = nil, version: Int? = nil) {
        self.id = id
        self.email = email
        self.publicKey = publicKey
        self.encryptedPrivateKey = encryptedPrivateKey
        self.kdfParams = kdfParams
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case publicKey = "public_key"
        case encryptedPrivateKey = "encrypted_private_key"
        case kdfParams = "kdf_params"
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(publicKey, forKey: .publicKey)
        try container.encodeIfPresent(encryptedPrivateKey, forKey: .encryptedPrivateKey)
        try container.encodeIfPresent(kdfParams, forKey: .kdfParams)
        try container.encodeIfPresent(version, forKey: .version)
    }
}


extension GetEncryptionKey200Response: Identifiable {}
