//
// GetIntegrationsSummary200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetIntegrationsSummary200Response: Sendable, Codable, Hashable {

    public var apiRequestsToday: Int?
    public var activeApiKeys: Int?
    public var apiKeys: [GetIntegrationsSummary200ResponseApiKeysInner]?
    public var webhookFailures: Int?
    public var webhooksTotal: Int?
    public var webhooks: [GetIntegrationsSummary200ResponseWebhooksInner]?
    public var generatedAt: Date?

    public init(apiRequestsToday: Int? = nil, activeApiKeys: Int? = nil, apiKeys: [GetIntegrationsSummary200ResponseApiKeysInner]? = nil, webhookFailures: Int? = nil, webhooksTotal: Int? = nil, webhooks: [GetIntegrationsSummary200ResponseWebhooksInner]? = nil, generatedAt: Date? = nil) {
        self.apiRequestsToday = apiRequestsToday
        self.activeApiKeys = activeApiKeys
        self.apiKeys = apiKeys
        self.webhookFailures = webhookFailures
        self.webhooksTotal = webhooksTotal
        self.webhooks = webhooks
        self.generatedAt = generatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apiRequestsToday = "api_requests_today"
        case activeApiKeys = "active_api_keys"
        case apiKeys = "api_keys"
        case webhookFailures = "webhook_failures"
        case webhooksTotal = "webhooks_total"
        case webhooks
        case generatedAt = "generated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(apiRequestsToday, forKey: .apiRequestsToday)
        try container.encodeIfPresent(activeApiKeys, forKey: .activeApiKeys)
        try container.encodeIfPresent(apiKeys, forKey: .apiKeys)
        try container.encodeIfPresent(webhookFailures, forKey: .webhookFailures)
        try container.encodeIfPresent(webhooksTotal, forKey: .webhooksTotal)
        try container.encodeIfPresent(webhooks, forKey: .webhooks)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
    }
}

