//
// GetSecurity200ResponseStatsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSecurity200ResponseStatsInner: Sendable, Codable, Hashable {

    public var label: String?
    public var value: Int?
    public var trend: String?

    public init(label: String? = nil, value: Int? = nil, trend: String? = nil) {
        self.label = label
        self.value = value
        self.trend = trend
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case value
        case trend
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(trend, forKey: .trend)
    }
}

