//
// GetSecurity200ResponseAlertsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSecurity200ResponseAlertsInner: Sendable, Codable, Hashable {

    public enum Level: String, Sendable, Codable, CaseIterable {
        case info = "info"
        case warning = "warning"
        case critical = "critical"
    }
    public var level: Level?
    public var message: String?
    public var time: Date?

    public init(level: Level? = nil, message: String? = nil, time: Date? = nil) {
        self.level = level
        self.message = message
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case level
        case message
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(level, forKey: .level)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(time, forKey: .time)
    }
}

