//
// GetStorage200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetStorage200Response: Sendable, Codable, Hashable {

    public var totalBytes: Int64?
    public var allocBytes: Int64?
    public var perSeatBytes: Int64?
    public var topMailboxes: [GetStorage200ResponseTopMailboxesInner]?
    public var topMessages: [GetStorage200ResponseTopMessagesInner]?
    public var generatedAt: Date?

    public init(totalBytes: Int64? = nil, allocBytes: Int64? = nil, perSeatBytes: Int64? = nil, topMailboxes: [GetStorage200ResponseTopMailboxesInner]? = nil, topMessages: [GetStorage200ResponseTopMessagesInner]? = nil, generatedAt: Date? = nil) {
        self.totalBytes = totalBytes
        self.allocBytes = allocBytes
        self.perSeatBytes = perSeatBytes
        self.topMailboxes = topMailboxes
        self.topMessages = topMessages
        self.generatedAt = generatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalBytes = "total_bytes"
        case allocBytes = "alloc_bytes"
        case perSeatBytes = "per_seat_bytes"
        case topMailboxes = "top_mailboxes"
        case topMessages = "top_messages"
        case generatedAt = "generated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalBytes, forKey: .totalBytes)
        try container.encodeIfPresent(allocBytes, forKey: .allocBytes)
        try container.encodeIfPresent(perSeatBytes, forKey: .perSeatBytes)
        try container.encodeIfPresent(topMailboxes, forKey: .topMailboxes)
        try container.encodeIfPresent(topMessages, forKey: .topMessages)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
    }
}

