//
// GetStorage200ResponseTopMessagesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetStorage200ResponseTopMessagesInner: Sendable, Codable, Hashable {

    public var sender: String?
    public var subject: String?
    public var sizeBytes: Int?
    public var filenames: [String]?
    public var queuedAt: Date?

    public init(sender: String? = nil, subject: String? = nil, sizeBytes: Int? = nil, filenames: [String]? = nil, queuedAt: Date? = nil) {
        self.sender = sender
        self.subject = subject
        self.sizeBytes = sizeBytes
        self.filenames = filenames
        self.queuedAt = queuedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sender
        case subject
        case sizeBytes = "size_bytes"
        case filenames
        case queuedAt = "queued_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sender, forKey: .sender)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encodeIfPresent(sizeBytes, forKey: .sizeBytes)
        try container.encodeIfPresent(filenames, forKey: .filenames)
        try container.encodeIfPresent(queuedAt, forKey: .queuedAt)
    }
}

