//
// GetSecurity200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSecurity200Response: Sendable, Codable, Hashable {

    public enum OverallStatus: String, Sendable, Codable, CaseIterable {
        case healthy = "healthy"
        case warning = "warning"
        case critical = "critical"
    }
    public var overallStatus: OverallStatus?
    public var stats: [GetSecurity200ResponseStatsInner]?
    public var alerts: [GetSecurity200ResponseAlertsInner]?

    public init(overallStatus: OverallStatus? = nil, stats: [GetSecurity200ResponseStatsInner]? = nil, alerts: [GetSecurity200ResponseAlertsInner]? = nil) {
        self.overallStatus = overallStatus
        self.stats = stats
        self.alerts = alerts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case overallStatus = "overall_status"
        case stats
        case alerts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(overallStatus, forKey: .overallStatus)
        try container.encodeIfPresent(stats, forKey: .stats)
        try container.encodeIfPresent(alerts, forKey: .alerts)
    }
}

