//
// GetStorage200ResponseTopMailboxesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetStorage200ResponseTopMailboxesInner: Sendable, Codable, Hashable {

    public var email: String?
    public var usageBytes: Int64?

    public init(email: String? = nil, usageBytes: Int64? = nil) {
        self.email = email
        self.usageBytes = usageBytes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case usageBytes = "usage_bytes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(usageBytes, forKey: .usageBytes)
    }
}

