//
// HealthzGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HealthzGet200Response: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case ok = "ok"
    }
    public var status: Status
    public var time: Date

    public init(status: Status, time: Date) {
        self.status = status
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(time, forKey: .time)
    }
}

