//
// ListUsers200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListUsers200Response: Sendable, Codable, Hashable {

    public var data: [User]
    public var limit: Int

    public init(data: [User], limit: Int) {
        self.data = data
        self.limit = limit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case limit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(limit, forKey: .limit)
    }
}

