//
// ListAddOns200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListAddOns200Response: Sendable, Codable, Hashable {

    public var addOns: [AddOn]

    public init(addOns: [AddOn]) {
        self.addOns = addOns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addOns = "add_ons"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(addOns, forKey: .addOns)
    }
}

