//
// MapMigrationRequestMappingsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MapMigrationRequestMappingsInner: Sendable, Codable, Hashable {

    public var sourceEmail: String
    public var destEmail: String

    public init(sourceEmail: String, destEmail: String) {
        self.sourceEmail = sourceEmail
        self.destEmail = destEmail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sourceEmail = "source_email"
        case destEmail = "dest_email"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sourceEmail, forKey: .sourceEmail)
        try container.encode(destEmail, forKey: .destEmail)
    }
}

