//
// MapMigrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MapMigrationRequest: Sendable, Codable, Hashable {

    public var mappings: [MapMigrationRequestMappingsInner]

    public init(mappings: [MapMigrationRequestMappingsInner]) {
        self.mappings = mappings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mappings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mappings, forKey: .mappings)
    }
}

