//
// MessageStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MessageStats: Sendable, Codable, Hashable {

    public var window: MessageStatsWindow?
    public var domain: String?
    public var sent: Int?
    public var counts: MessageStatsCounts?
    public var rates: MessageStatsRates?

    public init(window: MessageStatsWindow? = nil, domain: String? = nil, sent: Int? = nil, counts: MessageStatsCounts? = nil, rates: MessageStatsRates? = nil) {
        self.window = window
        self.domain = domain
        self.sent = sent
        self.counts = counts
        self.rates = rates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case window
        case domain
        case sent
        case counts
        case rates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(window, forKey: .window)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(sent, forKey: .sent)
        try container.encodeIfPresent(counts, forKey: .counts)
        try container.encodeIfPresent(rates, forKey: .rates)
    }
}

