//
// Message.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Message: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "queued"
        case sending = "sending"
        case delivered = "delivered"
        case bounced = "bounced"
        case deferred = "deferred"
        case complaint = "complaint"
    }
    public var id: UUID
    public var tenantId: UUID
    /** RFC 5322 Message-ID header, including angle brackets. */
    public var messageId: String
    public var sender: String
    public var recipients: [String]
    public var subject: String?
    public var status: Status
    public var queuedAt: Date
    public var updatedAt: Date
    public var bounceReason: String?
    public var sizeBytes: Int?

    public init(id: UUID, tenantId: UUID, messageId: String, sender: String, recipients: [String], subject: String? = nil, status: Status, queuedAt: Date, updatedAt: Date, bounceReason: String? = nil, sizeBytes: Int? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.messageId = messageId
        self.sender = sender
        self.recipients = recipients
        self.subject = subject
        self.status = status
        self.queuedAt = queuedAt
        self.updatedAt = updatedAt
        self.bounceReason = bounceReason
        self.sizeBytes = sizeBytes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case messageId = "message_id"
        case sender
        case recipients
        case subject
        case status
        case queuedAt = "queued_at"
        case updatedAt = "updated_at"
        case bounceReason = "bounce_reason"
        case sizeBytes = "size_bytes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(messageId, forKey: .messageId)
        try container.encode(sender, forKey: .sender)
        try container.encode(recipients, forKey: .recipients)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encode(status, forKey: .status)
        try container.encode(queuedAt, forKey: .queuedAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(bounceReason, forKey: .bounceReason)
        try container.encodeIfPresent(sizeBytes, forKey: .sizeBytes)
    }
}


extension Message: Identifiable {}
