//
// MessageDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single message with the content captured at send time. Returned only by GET /v1/messages/{id} (the list stays summary-only). Attachments are not returned.  */
public struct MessageDetail: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "queued"
        case sending = "sending"
        case delivered = "delivered"
        case bounced = "bounced"
        case deferred = "deferred"
        case complaint = "complaint"
    }
    public var id: UUID
    public var tenantId: UUID
    /** RFC 5322 Message-ID header, including angle brackets. */
    public var messageId: String
    public var sender: String
    public var recipients: [String]
    public var subject: String?
    public var status: Status
    public var queuedAt: Date
    public var updatedAt: Date
    public var bounceReason: String?
    public var sizeBytes: Int?
    public var from: String?
    public var to: [String]?
    public var cc: [String]?
    public var bcc: [String]?
    public var text: String?
    public var html: String?
    public var headers: [String: String]?

    public init(id: UUID, tenantId: UUID, messageId: String, sender: String, recipients: [String], subject: String? = nil, status: Status, queuedAt: Date, updatedAt: Date, bounceReason: String? = nil, sizeBytes: Int? = nil, from: String? = nil, to: [String]? = nil, cc: [String]? = nil, bcc: [String]? = nil, text: String? = nil, html: String? = nil, headers: [String: String]? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.messageId = messageId
        self.sender = sender
        self.recipients = recipients
        self.subject = subject
        self.status = status
        self.queuedAt = queuedAt
        self.updatedAt = updatedAt
        self.bounceReason = bounceReason
        self.sizeBytes = sizeBytes
        self.from = from
        self.to = to
        self.cc = cc
        self.bcc = bcc
        self.text = text
        self.html = html
        self.headers = headers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case messageId = "message_id"
        case sender
        case recipients
        case subject
        case status
        case queuedAt = "queued_at"
        case updatedAt = "updated_at"
        case bounceReason = "bounce_reason"
        case sizeBytes = "size_bytes"
        case from
        case to
        case cc
        case bcc
        case text
        case html
        case headers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(messageId, forKey: .messageId)
        try container.encode(sender, forKey: .sender)
        try container.encode(recipients, forKey: .recipients)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encode(status, forKey: .status)
        try container.encode(queuedAt, forKey: .queuedAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(bounceReason, forKey: .bounceReason)
        try container.encodeIfPresent(sizeBytes, forKey: .sizeBytes)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(cc, forKey: .cc)
        try container.encodeIfPresent(bcc, forKey: .bcc)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(html, forKey: .html)
        try container.encodeIfPresent(headers, forKey: .headers)
    }
}


extension MessageDetail: Identifiable {}
