//
// MigrationProgress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MigrationProgress: Sendable, Codable, Hashable {

    public var migrationId: UUID
    public var status: String
    public var totalMailboxes: Int
    public var completedMailboxes: Int
    public var failedMailboxes: Int
    public var totalMessages: Int
    public var syncedMessages: Int
    public var failedMessages: Int
    public var percentComplete: Double
    public var mailboxes: [MigrationProgressMailboxesInner]

    public init(migrationId: UUID, status: String, totalMailboxes: Int, completedMailboxes: Int, failedMailboxes: Int, totalMessages: Int, syncedMessages: Int, failedMessages: Int, percentComplete: Double, mailboxes: [MigrationProgressMailboxesInner]) {
        self.migrationId = migrationId
        self.status = status
        self.totalMailboxes = totalMailboxes
        self.completedMailboxes = completedMailboxes
        self.failedMailboxes = failedMailboxes
        self.totalMessages = totalMessages
        self.syncedMessages = syncedMessages
        self.failedMessages = failedMessages
        self.percentComplete = percentComplete
        self.mailboxes = mailboxes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case migrationId = "migration_id"
        case status
        case totalMailboxes = "total_mailboxes"
        case completedMailboxes = "completed_mailboxes"
        case failedMailboxes = "failed_mailboxes"
        case totalMessages = "total_messages"
        case syncedMessages = "synced_messages"
        case failedMessages = "failed_messages"
        case percentComplete = "percent_complete"
        case mailboxes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(migrationId, forKey: .migrationId)
        try container.encode(status, forKey: .status)
        try container.encode(totalMailboxes, forKey: .totalMailboxes)
        try container.encode(completedMailboxes, forKey: .completedMailboxes)
        try container.encode(failedMailboxes, forKey: .failedMailboxes)
        try container.encode(totalMessages, forKey: .totalMessages)
        try container.encode(syncedMessages, forKey: .syncedMessages)
        try container.encode(failedMessages, forKey: .failedMessages)
        try container.encode(percentComplete, forKey: .percentComplete)
        try container.encode(mailboxes, forKey: .mailboxes)
    }
}

