//
// MigrationSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MigrationSettings: Sendable, Codable, Hashable {

    public var maxConcurrentMailboxes: Int?
    public var maxConcurrentMessages: Int?
    public var sourceRateLimit: Int?
    public var batchSize: Int?
    public var skipFolders: [String]?

    public init(maxConcurrentMailboxes: Int? = nil, maxConcurrentMessages: Int? = nil, sourceRateLimit: Int? = nil, batchSize: Int? = nil, skipFolders: [String]? = nil) {
        self.maxConcurrentMailboxes = maxConcurrentMailboxes
        self.maxConcurrentMessages = maxConcurrentMessages
        self.sourceRateLimit = sourceRateLimit
        self.batchSize = batchSize
        self.skipFolders = skipFolders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxConcurrentMailboxes = "max_concurrent_mailboxes"
        case maxConcurrentMessages = "max_concurrent_messages"
        case sourceRateLimit = "source_rate_limit"
        case batchSize = "batch_size"
        case skipFolders = "skip_folders"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxConcurrentMailboxes, forKey: .maxConcurrentMailboxes)
        try container.encodeIfPresent(maxConcurrentMessages, forKey: .maxConcurrentMessages)
        try container.encodeIfPresent(sourceRateLimit, forKey: .sourceRateLimit)
        try container.encodeIfPresent(batchSize, forKey: .batchSize)
        try container.encodeIfPresent(skipFolders, forKey: .skipFolders)
    }
}

