//
// MigrationCredential.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MigrationCredential: Sendable, Codable, Hashable {

    public enum Provider: String, Sendable, Codable, CaseIterable {
        case imap = "imap"
        case google = "google"
        case microsoft = "microsoft"
        case generic = "generic"
    }
    public var id: UUID
    public var tenantId: UUID
    public var provider: Provider
    public var encryptionKeyId: String?
    public var label: String?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, tenantId: UUID, provider: Provider, encryptionKeyId: String? = nil, label: String? = nil, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.tenantId = tenantId
        self.provider = provider
        self.encryptionKeyId = encryptionKeyId
        self.label = label
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case provider
        case encryptionKeyId = "encryption_key_id"
        case label
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(encryptionKeyId, forKey: .encryptionKeyId)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension MigrationCredential: Identifiable {}
