//
// ReplaceDistributionListMembersRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReplaceDistributionListMembersRequest: Sendable, Codable, Hashable {

    public var members: [String]

    public init(members: [String]) {
        self.members = members
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case members
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(members, forKey: .members)
    }
}

