//
// Resource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Resource: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case meetingRoom = "meeting_room"
        case equipment = "equipment"
    }
    public var id: UUID
    public var tenantId: UUID
    public var name: String
    public var type: ModelType
    public var capacity: Int?
    public var status: String
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, tenantId: UUID, name: String, type: ModelType, capacity: Int? = nil, status: String, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.tenantId = tenantId
        self.name = name
        self.type = type
        self.capacity = capacity
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case name
        case type
        case capacity
        case status
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(capacity, forKey: .capacity)
        try container.encode(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension Resource: Identifiable {}
