//
// SignupRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SignupRequest: Sendable, Codable, Hashable {

    public enum Mode: String, Sendable, Codable, CaseIterable {
        case api = "api"
        case business = "business"
        case both = "both"
    }
    public static let passwordRule = StringRule(minLength: 12, maxLength: nil, pattern: nil)
    public var slug: String
    public var displayName: String?
    public var adminEmail: String
    public var password: String
    public var mode: Mode? = .business

    public init(slug: String, displayName: String? = nil, adminEmail: String, password: String, mode: Mode? = .business) {
        self.slug = slug
        self.displayName = displayName
        self.adminEmail = adminEmail
        self.password = password
        self.mode = mode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slug
        case displayName = "display_name"
        case adminEmail = "admin_email"
        case password
        case mode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slug, forKey: .slug)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encode(adminEmail, forKey: .adminEmail)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(mode, forKey: .mode)
    }
}

