//
// StartMigration202Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StartMigration202Response: Sendable, Codable, Hashable {

    public var status: String
    public var mailboxesQueued: Int

    public init(status: String, mailboxesQueued: Int) {
        self.status = status
        self.mailboxesQueued = mailboxesQueued
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case mailboxesQueued = "mailboxes_queued"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(mailboxesQueued, forKey: .mailboxesQueued)
    }
}

