//
// Template.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Template: Sendable, Codable, Hashable {

    public var id: UUID?
    public var name: String?
    public var subject: String?
    public var html: String?
    public var text: String?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: UUID? = nil, name: String? = nil, subject: String? = nil, html: String? = nil, text: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.name = name
        self.subject = subject
        self.html = html
        self.text = text
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case subject
        case html
        case text
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encodeIfPresent(html, forKey: .html)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


extension Template: Identifiable {}
