//
// Tenant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Tenant: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case active = "active"
        case suspended = "suspended"
        case closing = "closing"
        case closed = "closed"
    }
    public var id: UUID
    public var slug: String
    public var displayName: String
    public var status: Status
    public var plan: String
    /** Per-tenant share of the per-VPS 5/min outbound cap (L6). */
    public var rateCapPerMin: Int
    public var dailyMsgQuota: Int
    public var adminEmail: String
    public var createdAt: Date
    public var suspendedAt: Date?
    public var closedAt: Date?
    public var hardDeleteAfter: Date?

    public init(id: UUID, slug: String, displayName: String, status: Status, plan: String, rateCapPerMin: Int, dailyMsgQuota: Int, adminEmail: String, createdAt: Date, suspendedAt: Date? = nil, closedAt: Date? = nil, hardDeleteAfter: Date? = nil) {
        self.id = id
        self.slug = slug
        self.displayName = displayName
        self.status = status
        self.plan = plan
        self.rateCapPerMin = rateCapPerMin
        self.dailyMsgQuota = dailyMsgQuota
        self.adminEmail = adminEmail
        self.createdAt = createdAt
        self.suspendedAt = suspendedAt
        self.closedAt = closedAt
        self.hardDeleteAfter = hardDeleteAfter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case slug
        case displayName = "display_name"
        case status
        case plan
        case rateCapPerMin = "rate_cap_per_min"
        case dailyMsgQuota = "daily_msg_quota"
        case adminEmail = "admin_email"
        case createdAt = "created_at"
        case suspendedAt = "suspended_at"
        case closedAt = "closed_at"
        case hardDeleteAfter = "hard_delete_after"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(slug, forKey: .slug)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(status, forKey: .status)
        try container.encode(plan, forKey: .plan)
        try container.encode(rateCapPerMin, forKey: .rateCapPerMin)
        try container.encode(dailyMsgQuota, forKey: .dailyMsgQuota)
        try container.encode(adminEmail, forKey: .adminEmail)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(suspendedAt, forKey: .suspendedAt)
        try container.encodeIfPresent(closedAt, forKey: .closedAt)
        try container.encodeIfPresent(hardDeleteAfter, forKey: .hardDeleteAfter)
    }
}


extension Tenant: Identifiable {}
