//
// UpdateCalendarMemberRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateCalendarMemberRequest: Sendable, Codable, Hashable {

    public enum Role: String, Sendable, Codable, CaseIterable {
        case viewer = "viewer"
        case editor = "editor"
        case owner = "owner"
    }
    public var role: Role

    public init(role: Role) {
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
    }
}

