//
// UpdateResourceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateResourceRequest: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case meetingRoom = "meeting_room"
        case equipment = "equipment"
    }
    public enum Status: String, Sendable, Codable, CaseIterable {
        case available = "available"
        case active = "active"
        case disabled = "disabled"
    }
    public var name: String?
    public var type: ModelType?
    public var capacity: Int?
    public var status: Status?

    public init(name: String? = nil, type: ModelType? = nil, capacity: Int? = nil, status: Status? = nil) {
        self.name = name
        self.type = type
        self.capacity = capacity
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case capacity
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(capacity, forKey: .capacity)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

