//
// UpdateContactListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateContactListRequest: Sendable, Codable, Hashable {

    public enum Visibility: String, Sendable, Codable, CaseIterable {
        case companyWide = "company_wide"
        case restricted = "restricted"
    }
    public var name: String?
    public var description: String?
    public var visibility: Visibility?

    public init(name: String? = nil, description: String? = nil, visibility: Visibility? = nil) {
        self.name = name
        self.description = description
        self.visibility = visibility
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case visibility
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(visibility, forKey: .visibility)
    }
}

