//
// UpdateDirectoryPermissionsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateDirectoryPermissionsRequest: Sendable, Codable, Hashable {

    public enum ContactViewAccess: String, Sendable, Codable, CaseIterable {
        case allUsers = "all_users"
        case sameDepartment = "same_department"
        case adminsOnly = "admins_only"
    }
    public enum ContactEditAccess: String, Sendable, Codable, CaseIterable {
        case allUsers = "all_users"
        case adminsOnly = "admins_only"
    }
    public enum ListManageAccess: String, Sendable, Codable, CaseIterable {
        case allUsers = "all_users"
        case listOwners = "list_owners"
        case adminsOnly = "admins_only"
    }
    public enum ExternalSharing: String, Sendable, Codable, CaseIterable {
        case allowed = "allowed"
        case restricted = "restricted"
        case disabled = "disabled"
    }
    public var contactViewAccess: ContactViewAccess?
    public var contactEditAccess: ContactEditAccess?
    public var listManageAccess: ListManageAccess?
    public var externalSharing: ExternalSharing?

    public init(contactViewAccess: ContactViewAccess? = nil, contactEditAccess: ContactEditAccess? = nil, listManageAccess: ListManageAccess? = nil, externalSharing: ExternalSharing? = nil) {
        self.contactViewAccess = contactViewAccess
        self.contactEditAccess = contactEditAccess
        self.listManageAccess = listManageAccess
        self.externalSharing = externalSharing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contactViewAccess = "contact_view_access"
        case contactEditAccess = "contact_edit_access"
        case listManageAccess = "list_manage_access"
        case externalSharing = "external_sharing"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contactViewAccess, forKey: .contactViewAccess)
        try container.encodeIfPresent(contactEditAccess, forKey: .contactEditAccess)
        try container.encodeIfPresent(listManageAccess, forKey: .listManageAccess)
        try container.encodeIfPresent(externalSharing, forKey: .externalSharing)
    }
}

