//
// UpdateCalendarEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateCalendarEventRequest: Sendable, Codable, Hashable {

    public var title: String?
    public var description: String?
    public var location: String?
    public var startsAt: Date?
    public var endsAt: Date?
    public var allDay: Bool?

    public init(title: String? = nil, description: String? = nil, location: String? = nil, startsAt: Date? = nil, endsAt: Date? = nil, allDay: Bool? = nil) {
        self.title = title
        self.description = description
        self.location = location
        self.startsAt = startsAt
        self.endsAt = endsAt
        self.allDay = allDay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case description
        case location
        case startsAt = "starts_at"
        case endsAt = "ends_at"
        case allDay = "all_day"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(startsAt, forKey: .startsAt)
        try container.encodeIfPresent(endsAt, forKey: .endsAt)
        try container.encodeIfPresent(allDay, forKey: .allDay)
    }
}

