//
// UpdateUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateUserRequest: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case active = "active"
        case suspended = "suspended"
        case deprovisioned = "deprovisioned"
    }
    public var firstName: String?
    public var lastName: String?
    public var title: String?
    public var department: String?
    public var status: Status?

    public init(firstName: String? = nil, lastName: String? = nil, title: String? = nil, department: String? = nil, status: Status? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.title = title
        self.department = department
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName = "first_name"
        case lastName = "last_name"
        case title
        case department
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

