//
// UserEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserEvent: Sendable, Codable, Hashable {

    public var email: String?
    public var eventAt: Date?
    public var daysInactive: Int?

    public init(email: String? = nil, eventAt: Date? = nil, daysInactive: Int? = nil) {
        self.email = email
        self.eventAt = eventAt
        self.daysInactive = daysInactive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case eventAt = "event_at"
        case daysInactive = "days_inactive"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(eventAt, forKey: .eventAt)
        try container.encodeIfPresent(daysInactive, forKey: .daysInactive)
    }
}

