//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct User: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case active = "active"
        case suspended = "suspended"
        case deprovisioned = "deprovisioned"
    }
    public var id: UUID
    public var tenantId: UUID
    public var email: String
    public var firstName: String
    public var lastName: String
    public var title: String?
    public var department: String?
    public var status: Status
    public var createdAt: Date
    public var updatedAt: Date
    public var mailboxCount: Int?

    public init(id: UUID, tenantId: UUID, email: String, firstName: String, lastName: String, title: String? = nil, department: String? = nil, status: Status, createdAt: Date, updatedAt: Date, mailboxCount: Int? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.title = title
        self.department = department
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.mailboxCount = mailboxCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case email
        case firstName = "first_name"
        case lastName = "last_name"
        case title
        case department
        case status
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case mailboxCount = "mailbox_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(email, forKey: .email)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(department, forKey: .department)
        try container.encode(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(mailboxCount, forKey: .mailboxCount)
    }
}


extension User: Identifiable {}
