//
// V1AdminsIdPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1AdminsIdPatchRequest: Sendable, Codable, Hashable {

    public enum Role: String, Sendable, Codable, CaseIterable {
        case admin = "admin"
        case viewer = "viewer"
    }
    public static let passwordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    public var password: String?
    public var displayName: String?
    public var role: Role?
    public var disabled: Bool?

    public init(password: String? = nil, displayName: String? = nil, role: Role? = nil, disabled: Bool? = nil) {
        self.password = password
        self.displayName = displayName
        self.role = role
        self.disabled = disabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case password
        case displayName = "display_name"
        case role
        case disabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(disabled, forKey: .disabled)
    }
}

