//
// V1AdminsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1AdminsPostRequest: Sendable, Codable, Hashable {

    public enum Role: String, Sendable, Codable, CaseIterable {
        case admin = "admin"
        case viewer = "viewer"
    }
    public static let passwordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    public var email: String
    public var password: String?
    public var displayName: String?
    public var role: Role? = .admin

    public init(email: String, password: String? = nil, displayName: String? = nil, role: Role? = .admin) {
        self.email = email
        self.password = password
        self.displayName = displayName
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case displayName = "display_name"
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

