//
// V1AdminLoginPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1AdminLoginPost200Response: Sendable, Codable, Hashable {

    public var token: String
    public var expiresAt: Date
    public var admin: Admin
    public var tenant: Tenant

    public init(token: String, expiresAt: Date, admin: Admin, tenant: Tenant) {
        self.token = token
        self.expiresAt = expiresAt
        self.admin = admin
        self.tenant = tenant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case expiresAt = "expires_at"
        case admin
        case tenant
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(admin, forKey: .admin)
        try container.encode(tenant, forKey: .tenant)
    }
}

