//
// V1AliasesPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1AliasesPostRequest: Sendable, Codable, Hashable {

    public var aliasAddress: String
    public var aliasTarget: String

    public init(aliasAddress: String, aliasTarget: String) {
        self.aliasAddress = aliasAddress
        self.aliasTarget = aliasTarget
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aliasAddress = "alias_address"
        case aliasTarget = "alias_target"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aliasAddress, forKey: .aliasAddress)
        try container.encode(aliasTarget, forKey: .aliasTarget)
    }
}

