//
// V1ApiKeysPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1ApiKeysPostRequest: Sendable, Codable, Hashable {

    public enum Scopes: String, Sendable, Codable, CaseIterable {
        case tenantRead = "tenant:read"
        case tenantAdmin = "tenant:admin"
        case mailboxesRead = "mailboxes:read"
        case mailboxesWrite = "mailboxes:write"
        case sendRead = "send:read"
        case sendWrite = "send:write"
        case webhooksRead = "webhooks:read"
        case webhooksWrite = "webhooks:write"
        case domainsRead = "domains:read"
        case domainsWrite = "domains:write"
    }
    public static let scopesRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    /** Free-text identifier shown in the dashboard. */
    public var label: String
    /** Allowed scopes on this key. */
    public var scopes: [Scopes]

    public init(label: String, scopes: [Scopes]) {
        self.label = label
        self.scopes = scopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case scopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(label, forKey: .label)
        try container.encode(scopes, forKey: .scopes)
    }
}

