//
// V1ApiKeysPost201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1ApiKeysPost201Response: Sendable, Codable, Hashable {

    public var id: UUID
    public var tenantId: UUID
    /** 8-char public prefix; safe to store and display. */
    public var _prefix: String
    public var scopes: [String]
    public var label: String
    public var lastUsedAt: Date?
    public var revokedAt: Date?
    public var createdAt: Date
    /** The full `lk_live_<prefix>_<secret>` token. Shown ONCE. */
    public var secret: String

    public init(id: UUID, tenantId: UUID, _prefix: String, scopes: [String], label: String, lastUsedAt: Date? = nil, revokedAt: Date? = nil, createdAt: Date, secret: String) {
        self.id = id
        self.tenantId = tenantId
        self._prefix = _prefix
        self.scopes = scopes
        self.label = label
        self.lastUsedAt = lastUsedAt
        self.revokedAt = revokedAt
        self.createdAt = createdAt
        self.secret = secret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case _prefix = "prefix"
        case scopes
        case label
        case lastUsedAt = "last_used_at"
        case revokedAt = "revoked_at"
        case createdAt = "created_at"
        case secret
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(_prefix, forKey: ._prefix)
        try container.encode(scopes, forKey: .scopes)
        try container.encode(label, forKey: .label)
        try container.encodeIfPresent(lastUsedAt, forKey: .lastUsedAt)
        try container.encodeIfPresent(revokedAt, forKey: .revokedAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(secret, forKey: .secret)
    }
}


extension V1ApiKeysPost201Response: Identifiable {}
