//
// V1InboxesMailboxMessagesPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1InboxesMailboxMessagesPostRequest: Sendable, Codable, Hashable {

    public var to: [String]
    public var cc: [String]?
    public var subject: String?
    public var text: String
    public var html: String?

    public init(to: [String], cc: [String]? = nil, subject: String? = nil, text: String, html: String? = nil) {
        self.to = to
        self.cc = cc
        self.subject = subject
        self.text = text
        self.html = html
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case to
        case cc
        case subject
        case text
        case html
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(to, forKey: .to)
        try container.encodeIfPresent(cc, forKey: .cc)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encode(text, forKey: .text)
        try container.encodeIfPresent(html, forKey: .html)
    }
}

