//
// V1MailboxesEmailPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1MailboxesEmailPatchRequest: Sendable, Codable, Hashable {

    public static let passwordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    public static let quotaBytesRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var password: String?
    public var quotaBytes: Int64?
    public var disabled: Bool?

    public init(password: String? = nil, quotaBytes: Int64? = nil, disabled: Bool? = nil) {
        self.password = password
        self.quotaBytes = quotaBytes
        self.disabled = disabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case password
        case quotaBytes = "quota_bytes"
        case disabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(quotaBytes, forKey: .quotaBytes)
        try container.encodeIfPresent(disabled, forKey: .disabled)
    }
}

