//
// V1MailboxesEmailExportPost201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1MailboxesEmailExportPost201Response: Sendable, Codable, Hashable {

    public enum Format: String, Sendable, Codable, CaseIterable {
        case mbox = "mbox"
    }
    /** Relative download URL. Caller appends to the API host. */
    public var url: String
    public var expiresAt: Date
    public var format: Format

    public init(url: String, expiresAt: Date, format: Format) {
        self.url = url
        self.expiresAt = expiresAt
        self.format = format
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case expiresAt = "expires_at"
        case format
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(format, forKey: .format)
    }
}

