//
// V1SendPostRequestAttachmentsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1SendPostRequestAttachmentsInner: Sendable, Codable, Hashable {

    public var filename: String
    public var contentType: String
    /** Base64-encoded body, max 10 MB decoded per attachment. */
    public var contentBase64: String

    public init(filename: String, contentType: String, contentBase64: String) {
        self.filename = filename
        self.contentType = contentType
        self.contentBase64 = contentBase64
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filename
        case contentType = "content_type"
        case contentBase64 = "content_base64"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filename, forKey: .filename)
        try container.encode(contentType, forKey: .contentType)
        try container.encode(contentBase64, forKey: .contentBase64)
    }
}

