//
// V1SendPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1SendPostRequest: Sendable, Codable, Hashable {

    public static let toRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var from: String
    public var to: [String]
    public var cc: [String]?
    public var bcc: [String]?
    public var subject: String?
    /** Plain-text body. Required if `html` is absent. */
    public var text: String?
    /** HTML body. Required if `text` is absent. */
    public var html: String?
    public var headers: [String: String]?
    /** Mark as opt-in/broadcast: skips suppressed recipients and adds a managed one-click List-Unsubscribe header. */
    public var unsubscribe: Bool?
    /** Render subject/text/html from a stored template (GET /v1/templates). Mutually exclusive with inline subject/text/html. */
    public var templateId: UUID?
    /** Values substituted into the template's {{variable}} placeholders. */
    public var variables: [String: String]?
    /** Schedule delivery for a future RFC3339 time (≤ 30 days out). Omit or past = send now. Cancel with DELETE /v1/messages/{id} while scheduled. */
    public var sendAt: Date?
    public var attachments: [V1SendPostRequestAttachmentsInner]?

    public init(from: String, to: [String], cc: [String]? = nil, bcc: [String]? = nil, subject: String? = nil, text: String? = nil, html: String? = nil, headers: [String: String]? = nil, unsubscribe: Bool? = nil, templateId: UUID? = nil, variables: [String: String]? = nil, sendAt: Date? = nil, attachments: [V1SendPostRequestAttachmentsInner]? = nil) {
        self.from = from
        self.to = to
        self.cc = cc
        self.bcc = bcc
        self.subject = subject
        self.text = text
        self.html = html
        self.headers = headers
        self.unsubscribe = unsubscribe
        self.templateId = templateId
        self.variables = variables
        self.sendAt = sendAt
        self.attachments = attachments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case to
        case cc
        case bcc
        case subject
        case text
        case html
        case headers
        case unsubscribe
        case templateId = "template_id"
        case variables
        case sendAt = "send_at"
        case attachments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encodeIfPresent(cc, forKey: .cc)
        try container.encodeIfPresent(bcc, forKey: .bcc)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(html, forKey: .html)
        try container.encodeIfPresent(headers, forKey: .headers)
        try container.encodeIfPresent(unsubscribe, forKey: .unsubscribe)
        try container.encodeIfPresent(templateId, forKey: .templateId)
        try container.encodeIfPresent(variables, forKey: .variables)
        try container.encodeIfPresent(sendAt, forKey: .sendAt)
        try container.encodeIfPresent(attachments, forKey: .attachments)
    }
}

