//
// V1SendPost202Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1SendPost202Response: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "queued"
        case scheduled = "scheduled"
    }
    /** Lockally identifier; use with GET /v1/messages/{id}. */
    public var id: UUID
    /** RFC 5322 Message-ID (with angle brackets). */
    public var messageId: String
    /** \"scheduled\" when send_at is in the future. */
    public var status: Status
    public var warning: String?

    public init(id: UUID, messageId: String, status: Status, warning: String? = nil) {
        self.id = id
        self.messageId = messageId
        self.status = status
        self.warning = warning
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case messageId = "message_id"
        case status
        case warning
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(messageId, forKey: .messageId)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(warning, forKey: .warning)
    }
}


extension V1SendPost202Response: Identifiable {}
