//
// V1WebhooksIdPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1WebhooksIdPatchRequest: Sendable, Codable, Hashable {

    public var url: String?
    public var events: [String]?
    public var paused: Bool?

    public init(url: String? = nil, events: [String]? = nil, paused: Bool? = nil) {
        self.url = url
        self.events = events
        self.paused = paused
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case events
        case paused
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encodeIfPresent(paused, forKey: .paused)
    }
}

