//
// V1WebhooksPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V1WebhooksPostRequest: Sendable, Codable, Hashable {

    public static let eventsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    /** HTTPS recommended (HTTP allowed for local development). */
    public var url: String
    public var events: [String]

    public init(url: String, events: [String]) {
        self.url = url
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(events, forKey: .events)
    }
}

