//
// VacationResponder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VacationResponder: Sendable, Codable, Hashable {

    public var mailboxEmail: String
    public var enabled: Bool
    public var params: VacationParams
    /** Pre-rendered Sieve script (RFC 5230). */
    public var script: String
    /** Null = stored on lockally but not yet pushed to the mail server. */
    public var syncedAt: Date?
    public var createdAt: Date
    public var updatedAt: Date

    public init(mailboxEmail: String, enabled: Bool, params: VacationParams, script: String, syncedAt: Date? = nil, createdAt: Date, updatedAt: Date) {
        self.mailboxEmail = mailboxEmail
        self.enabled = enabled
        self.params = params
        self.script = script
        self.syncedAt = syncedAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mailboxEmail = "mailbox_email"
        case enabled
        case params
        case script
        case syncedAt = "synced_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mailboxEmail, forKey: .mailboxEmail)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(params, forKey: .params)
        try container.encode(script, forKey: .script)
        try container.encodeIfPresent(syncedAt, forKey: .syncedAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

