//
// Webhook.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Webhook: Sendable, Codable, Hashable {

    public var id: UUID
    public var tenantId: UUID
    public var url: String
    public var events: [String]
    public var paused: Bool
    public var pausedAt: Date?
    public var lastSuccessAt: Date?
    public var lastFailureAt: Date?
    public var consecutiveFailures: Int
    public var createdAt: Date
    /** Hex-encoded HMAC-SHA256 key. Present ONLY on POST response. */
    public var signingSecret: String?

    public init(id: UUID, tenantId: UUID, url: String, events: [String], paused: Bool, pausedAt: Date? = nil, lastSuccessAt: Date? = nil, lastFailureAt: Date? = nil, consecutiveFailures: Int, createdAt: Date, signingSecret: String? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.url = url
        self.events = events
        self.paused = paused
        self.pausedAt = pausedAt
        self.lastSuccessAt = lastSuccessAt
        self.lastFailureAt = lastFailureAt
        self.consecutiveFailures = consecutiveFailures
        self.createdAt = createdAt
        self.signingSecret = signingSecret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case url
        case events
        case paused
        case pausedAt = "paused_at"
        case lastSuccessAt = "last_success_at"
        case lastFailureAt = "last_failure_at"
        case consecutiveFailures = "consecutive_failures"
        case createdAt = "created_at"
        case signingSecret = "signing_secret"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(url, forKey: .url)
        try container.encode(events, forKey: .events)
        try container.encode(paused, forKey: .paused)
        try container.encodeIfPresent(pausedAt, forKey: .pausedAt)
        try container.encodeIfPresent(lastSuccessAt, forKey: .lastSuccessAt)
        try container.encodeIfPresent(lastFailureAt, forKey: .lastFailureAt)
        try container.encode(consecutiveFailures, forKey: .consecutiveFailures)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(signingSecret, forKey: .signingSecret)
    }
}


extension Webhook: Identifiable {}
