//
// AddOnsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AddOnsAPI {

    /**
     Activate an add-on
     
     - parameter name: (path) Add-on key 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ActivateAddOn200Response
     */
    open class func activateAddOn(name: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ActivateAddOn200Response {
        return try await activateAddOnWithRequestBuilder(name: name, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Activate an add-on
     - POST /v1/add-ons/{name}/activate
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter name: (path) Add-on key 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ActivateAddOn200Response> 
     */
    open class func activateAddOnWithRequestBuilder(name: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ActivateAddOn200Response> {
        var localVariablePath = "/v1/add-ons/{name}/activate"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ActivateAddOn200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Cancel an add-on
     
     - parameter name: (path) Add-on key 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func cancelAddOn(name: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await cancelAddOnWithRequestBuilder(name: name, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Cancel an add-on
     - POST /v1/add-ons/{name}/cancel
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter name: (path) Add-on key 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func cancelAddOnWithRequestBuilder(name: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/add-ons/{name}/cancel"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get add-on status
     
     - parameter name: (path) Add-on key 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetAddOnStatus200Response
     */
    open class func getAddOnStatus(name: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> GetAddOnStatus200Response {
        return try await getAddOnStatusWithRequestBuilder(name: name, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get add-on status
     - GET /v1/add-ons/{name}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter name: (path) Add-on key 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetAddOnStatus200Response> 
     */
    open class func getAddOnStatusWithRequestBuilder(name: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<GetAddOnStatus200Response> {
        var localVariablePath = "/v1/add-ons/{name}"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetAddOnStatus200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List add-ons
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListAddOns200Response
     */
    open class func listAddOns(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ListAddOns200Response {
        return try await listAddOnsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List add-ons
     - GET /v1/add-ons
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListAddOns200Response> 
     */
    open class func listAddOnsWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ListAddOns200Response> {
        let localVariablePath = "/v1/add-ons"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListAddOns200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
