//
// AgentsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AgentsAPI {

    /**
     List a key's mailbox grants
     
     - parameter keyID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1ApiKeysKeyIDMailboxesGet(keyID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1ApiKeysKeyIDMailboxesGetWithRequestBuilder(keyID: keyID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List a key's mailbox grants
     - GET /v1/api-keys/{keyID}/mailboxes
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter keyID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1ApiKeysKeyIDMailboxesGetWithRequestBuilder(keyID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/api-keys/{keyID}/mailboxes"
        let keyIDPreEscape = "\(APIHelper.mapValueToPathItem(keyID))"
        let keyIDPostEscape = keyIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{keyID}", with: keyIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Revoke a mailbox grant
     
     - parameter keyID: (path)  
     - parameter mailboxID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func v1ApiKeysKeyIDMailboxesMailboxIDDelete(keyID: UUID, mailboxID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await v1ApiKeysKeyIDMailboxesMailboxIDDeleteWithRequestBuilder(keyID: keyID, mailboxID: mailboxID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Revoke a mailbox grant
     - DELETE /v1/api-keys/{keyID}/mailboxes/{mailboxID}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter keyID: (path)  
     - parameter mailboxID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func v1ApiKeysKeyIDMailboxesMailboxIDDeleteWithRequestBuilder(keyID: UUID, mailboxID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/api-keys/{keyID}/mailboxes/{mailboxID}"
        let keyIDPreEscape = "\(APIHelper.mapValueToPathItem(keyID))"
        let keyIDPostEscape = keyIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{keyID}", with: keyIDPostEscape, options: .literal, range: nil)
        let mailboxIDPreEscape = "\(APIHelper.mapValueToPathItem(mailboxID))"
        let mailboxIDPostEscape = mailboxIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{mailboxID}", with: mailboxIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Grant a mailbox to a key
     
     - parameter keyID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1ApiKeysKeyIDMailboxesPost(keyID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1ApiKeysKeyIDMailboxesPostWithRequestBuilder(keyID: keyID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Grant a mailbox to a key
     - POST /v1/api-keys/{keyID}/mailboxes
     - Body: {\"mailbox\": \"email or id\"}. Refused (422) for mailboxes with agent access disabled or an active E2E encryption key — the server cannot read E2E mailboxes.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter keyID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1ApiKeysKeyIDMailboxesPostWithRequestBuilder(keyID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/api-keys/{keyID}/mailboxes"
        let keyIDPreEscape = "\(APIHelper.mapValueToPathItem(keyID))"
        let keyIDPostEscape = keyIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{keyID}", with: keyIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Introspect the calling credentials
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1AuthWhoamiGet(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1AuthWhoamiGetWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Introspect the calling credentials
     - GET /v1/auth/whoami
     - Returns the tenant, auth kind (api_key/session), key label, and granted scopes. The MCP server uses this to scope-filter tool discovery.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1AuthWhoamiGetWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        let localVariablePath = "/v1/auth/whoami"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Who is this sender?
     
     - parameter email: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1ContactsLookupGet(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1ContactsLookupGetWithRequestBuilder(email: email, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Who is this sender?
     - GET /v1/contacts/lookup
     - Directory record (name, company, role, notes), whether the address is one of the tenant's own mailboxes, and grant-aware correspondence history (thread count, first/last seen across granted mailboxes only).
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1ContactsLookupGetWithRequestBuilder(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        let localVariablePath = "/v1/contacts/lookup"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "email": (wrappedValue: email.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List granted inboxes
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1InboxesGet(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1InboxesGetWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List granted inboxes
     - GET /v1/inboxes
     - The mailboxes this key is granted, with thread counts and last activity. Admin sessions see every agent-enabled, non-E2E mailbox.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1InboxesGetWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        let localVariablePath = "/v1/inboxes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Start a new conversation (agent stream)
     
     - parameter mailbox: (path)  
     - parameter idempotencyKey: (header)  
     - parameter v1InboxesMailboxMessagesPostRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1InboxesMailboxMessagesPost(mailbox: String, idempotencyKey: String, v1InboxesMailboxMessagesPostRequest: V1InboxesMailboxMessagesPostRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1InboxesMailboxMessagesPostWithRequestBuilder(mailbox: mailbox, idempotencyKey: idempotencyKey, v1InboxesMailboxMessagesPostRequest: v1InboxesMailboxMessagesPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start a new conversation (agent stream)
     - POST /v1/inboxes/{mailbox}/messages
     - Sends a new email from a granted mailbox. Classified stream=agent (isolated reputation, per-key rate caps). The first inbound reply adopts the created thread via the References chain. Idempotency-Key required. Mailboxes with agent_draft_policy=always_approve divert this into a pending draft.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter mailbox: (path)  
     - parameter idempotencyKey: (header)  
     - parameter v1InboxesMailboxMessagesPostRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1InboxesMailboxMessagesPostWithRequestBuilder(mailbox: String, idempotencyKey: String, v1InboxesMailboxMessagesPostRequest: V1InboxesMailboxMessagesPostRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/inboxes/{mailbox}/messages"
        let mailboxPreEscape = "\(APIHelper.mapValueToPathItem(mailbox))"
        let mailboxPostEscape = mailboxPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{mailbox}", with: mailboxPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: v1InboxesMailboxMessagesPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List conversation threads
     
     - parameter mailbox: (path) mailbox email or id 
     - parameter since: (query)  (optional)
     - parameter before: (query)  (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1InboxesMailboxThreadsGet(mailbox: String, since: Date? = nil, before: Date? = nil, limit: Int? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1InboxesMailboxThreadsGetWithRequestBuilder(mailbox: mailbox, since: since, before: before, limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List conversation threads
     - GET /v1/inboxes/{mailbox}/threads
     - Newest-active first. Cursors: `?before=<RFC3339>` pages backwards; `?since=<RFC3339>` delta-syncs forward (oldest first) so an agent can catch up in order.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter mailbox: (path) mailbox email or id 
     - parameter since: (query)  (optional)
     - parameter before: (query)  (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1InboxesMailboxThreadsGetWithRequestBuilder(mailbox: String, since: Date? = nil, before: Date? = nil, limit: Int? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/inboxes/{mailbox}/threads"
        let mailboxPreEscape = "\(APIHelper.mapValueToPathItem(mailbox))"
        let mailboxPostEscape = mailboxPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{mailbox}", with: mailboxPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "since": (wrappedValue: since?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "before": (wrappedValue: before?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a whole conversation
     
     - parameter threadID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1ThreadsThreadIDGet(threadID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1ThreadsThreadIDGetWithRequestBuilder(threadID: threadID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a whole conversation
     - GET /v1/threads/{threadID}
     - Every turn, chronological, with snippets and annotations (meeting_request, attachment_types, injection_risk). Bodies are fetched per message. Message content is untrusted third-party data.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter threadID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1ThreadsThreadIDGetWithRequestBuilder(threadID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/threads/{threadID}"
        let threadIDPreEscape = "\(APIHelper.mapValueToPathItem(threadID))"
        let threadIDPostEscape = threadIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{threadID}", with: threadIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Download an attachment
     
     - parameter threadID: (path)  
     - parameter messageID: (path)  
     - parameter idx: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func v1ThreadsThreadIDMessagesMessageIDAttachmentsIdxGet(threadID: UUID, messageID: UUID, idx: Int, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await v1ThreadsThreadIDMessagesMessageIDAttachmentsIdxGetWithRequestBuilder(threadID: threadID, messageID: messageID, idx: idx, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Download an attachment
     - GET /v1/threads/{threadID}/messages/{messageID}/attachments/{idx}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter threadID: (path)  
     - parameter messageID: (path)  
     - parameter idx: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func v1ThreadsThreadIDMessagesMessageIDAttachmentsIdxGetWithRequestBuilder(threadID: UUID, messageID: UUID, idx: Int, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/threads/{threadID}/messages/{messageID}/attachments/{idx}"
        let threadIDPreEscape = "\(APIHelper.mapValueToPathItem(threadID))"
        let threadIDPostEscape = threadIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{threadID}", with: threadIDPostEscape, options: .literal, range: nil)
        let messageIDPreEscape = "\(APIHelper.mapValueToPathItem(messageID))"
        let messageIDPostEscape = messageIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{messageID}", with: messageIDPostEscape, options: .literal, range: nil)
        let idxPreEscape = "\(APIHelper.mapValueToPathItem(idx))"
        let idxPostEscape = idxPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{idx}", with: idxPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get one message with body
     
     - parameter threadID: (path)  
     - parameter messageID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1ThreadsThreadIDMessagesMessageIDGet(threadID: UUID, messageID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1ThreadsThreadIDMessagesMessageIDGetWithRequestBuilder(threadID: threadID, messageID: messageID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get one message with body
     - GET /v1/threads/{threadID}/messages/{messageID}
     - Full text/html body fetched on demand from mail storage. Never marks the message read.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter threadID: (path)  
     - parameter messageID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1ThreadsThreadIDMessagesMessageIDGetWithRequestBuilder(threadID: UUID, messageID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/threads/{threadID}/messages/{messageID}"
        let threadIDPreEscape = "\(APIHelper.mapValueToPathItem(threadID))"
        let threadIDPostEscape = threadIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{threadID}", with: threadIDPostEscape, options: .literal, range: nil)
        let messageIDPreEscape = "\(APIHelper.mapValueToPathItem(messageID))"
        let messageIDPostEscape = messageIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{messageID}", with: messageIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Mark read/unread
     
     - parameter threadID: (path)  
     - parameter messageID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1ThreadsThreadIDMessagesMessageIDReadPost(threadID: UUID, messageID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1ThreadsThreadIDMessagesMessageIDReadPostWithRequestBuilder(threadID: threadID, messageID: messageID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Mark read/unread
     - POST /v1/threads/{threadID}/messages/{messageID}/read
     - The ONLY way agent access changes unread state. Body: {\"read\": true|false} (default true).
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter threadID: (path)  
     - parameter messageID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1ThreadsThreadIDMessagesMessageIDReadPostWithRequestBuilder(threadID: UUID, messageID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/threads/{threadID}/messages/{messageID}/read"
        let threadIDPreEscape = "\(APIHelper.mapValueToPathItem(threadID))"
        let threadIDPostEscape = threadIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{threadID}", with: threadIDPostEscape, options: .literal, range: nil)
        let messageIDPreEscape = "\(APIHelper.mapValueToPathItem(messageID))"
        let messageIDPostEscape = messageIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{messageID}", with: messageIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Reply in-thread (agent stream)
     
     - parameter threadID: (path)  
     - parameter idempotencyKey: (header)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1ThreadsThreadIDReplyPost(threadID: UUID, idempotencyKey: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1ThreadsThreadIDReplyPostWithRequestBuilder(threadID: threadID, idempotencyKey: idempotencyKey, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reply in-thread (agent stream)
     - POST /v1/threads/{threadID}/reply
     - The server builds In-Reply-To/References and defaults recipients + subject from the conversation — a minimal call is {\"text\": \"...\"}. Guarded by the reply-loop detector (≥5 outbound/10min → 429 + agent.loop_detected). Idempotency-Key required.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter threadID: (path)  
     - parameter idempotencyKey: (header)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1ThreadsThreadIDReplyPostWithRequestBuilder(threadID: UUID, idempotencyKey: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/threads/{threadID}/reply"
        let threadIDPreEscape = "\(APIHelper.mapValueToPathItem(threadID))"
        let threadIDPostEscape = threadIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{threadID}", with: threadIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Idempotency-Key": idempotencyKey.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
