//
// BillingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class BillingAPI {

    /**
     Create a plan checkout session
     
     - parameter createBillingCheckoutRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateBillingCheckout200Response
     */
    open class func createBillingCheckout(createBillingCheckoutRequest: CreateBillingCheckoutRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CreateBillingCheckout200Response {
        return try await createBillingCheckoutWithRequestBuilder(createBillingCheckoutRequest: createBillingCheckoutRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a plan checkout session
     - POST /v1/billing/checkout
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createBillingCheckoutRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateBillingCheckout200Response> 
     */
    open class func createBillingCheckoutWithRequestBuilder(createBillingCheckoutRequest: CreateBillingCheckoutRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CreateBillingCheckout200Response> {
        let localVariablePath = "/v1/billing/checkout"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createBillingCheckoutRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateBillingCheckout200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create a send-units checkout session
     
     - parameter createUnitsCheckoutRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateUnitsCheckout200Response
     */
    open class func createUnitsCheckout(createUnitsCheckoutRequest: CreateUnitsCheckoutRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CreateUnitsCheckout200Response {
        return try await createUnitsCheckoutWithRequestBuilder(createUnitsCheckoutRequest: createUnitsCheckoutRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a send-units checkout session
     - POST /v1/billing/units/checkout
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createUnitsCheckoutRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateUnitsCheckout200Response> 
     */
    open class func createUnitsCheckoutWithRequestBuilder(createUnitsCheckoutRequest: CreateUnitsCheckoutRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CreateUnitsCheckout200Response> {
        let localVariablePath = "/v1/billing/units/checkout"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createUnitsCheckoutRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateUnitsCheckout200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get billing status
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BillingStatus
     */
    open class func getBilling(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> BillingStatus {
        return try await getBillingWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get billing status
     - GET /v1/billing
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BillingStatus> 
     */
    open class func getBillingWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<BillingStatus> {
        let localVariablePath = "/v1/billing"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BillingStatus>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
