//
// CalendarsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CalendarsAPI {

    /**
     Add a member to a calendar
     
     - parameter id: (path)  
     - parameter addCalendarMemberRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarMember
     */
    open class func addCalendarMember(id: UUID, addCalendarMemberRequest: AddCalendarMemberRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarMember {
        return try await addCalendarMemberWithRequestBuilder(id: id, addCalendarMemberRequest: addCalendarMemberRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add a member to a calendar
     - POST /v1/calendars/{id}/members
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter addCalendarMemberRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarMember> 
     */
    open class func addCalendarMemberWithRequestBuilder(id: UUID, addCalendarMemberRequest: AddCalendarMemberRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarMember> {
        var localVariablePath = "/v1/calendars/{id}/members"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addCalendarMemberRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarMember>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create a calendar
     
     - parameter createCalendarRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LockallyCalendar
     */
    open class func createCalendar(createCalendarRequest: CreateCalendarRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> LockallyCalendar {
        return try await createCalendarWithRequestBuilder(createCalendarRequest: createCalendarRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a calendar
     - POST /v1/calendars
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createCalendarRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LockallyCalendar> 
     */
    open class func createCalendarWithRequestBuilder(createCalendarRequest: CreateCalendarRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<LockallyCalendar> {
        let localVariablePath = "/v1/calendars"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCalendarRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LockallyCalendar>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create an event in a calendar
     
     - parameter id: (path)  
     - parameter createCalendarEventRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarEvent
     */
    open class func createCalendarEvent(id: UUID, createCalendarEventRequest: CreateCalendarEventRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarEvent {
        return try await createCalendarEventWithRequestBuilder(id: id, createCalendarEventRequest: createCalendarEventRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create an event in a calendar
     - POST /v1/calendars/{id}/events
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter createCalendarEventRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarEvent> 
     */
    open class func createCalendarEventWithRequestBuilder(id: UUID, createCalendarEventRequest: CreateCalendarEventRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarEvent> {
        var localVariablePath = "/v1/calendars/{id}/events"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCalendarEventRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarEvent>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create a calendar integration
     
     - parameter createCalendarIntegrationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarIntegration
     */
    open class func createCalendarIntegration(createCalendarIntegrationRequest: CreateCalendarIntegrationRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarIntegration {
        return try await createCalendarIntegrationWithRequestBuilder(createCalendarIntegrationRequest: createCalendarIntegrationRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a calendar integration
     - POST /v1/calendar-integrations
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createCalendarIntegrationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarIntegration> 
     */
    open class func createCalendarIntegrationWithRequestBuilder(createCalendarIntegrationRequest: CreateCalendarIntegrationRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarIntegration> {
        let localVariablePath = "/v1/calendar-integrations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCalendarIntegrationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarIntegration>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a calendar
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteCalendar(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteCalendarWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a calendar
     - DELETE /v1/calendars/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCalendarWithRequestBuilder(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/calendars/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a calendar event
     
     - parameter id: (path)  
     - parameter eventId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteCalendarEvent(id: UUID, eventId: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteCalendarEventWithRequestBuilder(id: id, eventId: eventId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a calendar event
     - DELETE /v1/calendars/{id}/events/{eventId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter eventId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCalendarEventWithRequestBuilder(id: UUID, eventId: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/calendars/{id}/events/{eventId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a calendar integration
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteCalendarIntegration(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteCalendarIntegrationWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a calendar integration
     - DELETE /v1/calendar-integrations/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCalendarIntegrationWithRequestBuilder(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/calendar-integrations/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a calendar
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LockallyCalendar
     */
    open class func getCalendar(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> LockallyCalendar {
        return try await getCalendarWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a calendar
     - GET /v1/calendars/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LockallyCalendar> 
     */
    open class func getCalendarWithRequestBuilder(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<LockallyCalendar> {
        var localVariablePath = "/v1/calendars/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LockallyCalendar>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get calendar policies
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarPolicies
     */
    open class func getCalendarPolicies(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarPolicies {
        return try await getCalendarPoliciesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get calendar policies
     - GET /v1/calendar-policies
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarPolicies> 
     */
    open class func getCalendarPoliciesWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarPolicies> {
        let localVariablePath = "/v1/calendar-policies"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarPolicies>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get calendar security overview
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetCalendarSecurity200Response
     */
    open class func getCalendarSecurity(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> GetCalendarSecurity200Response {
        return try await getCalendarSecurityWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get calendar security overview
     - GET /v1/calendar-security
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetCalendarSecurity200Response> 
     */
    open class func getCalendarSecurityWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<GetCalendarSecurity200Response> {
        let localVariablePath = "/v1/calendar-security"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetCalendarSecurity200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List events in a calendar
     
     - parameter id: (path)  
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListCalendarEvents200Response
     */
    open class func listCalendarEvents(id: UUID, from: Date? = nil, to: Date? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ListCalendarEvents200Response {
        return try await listCalendarEventsWithRequestBuilder(id: id, from: from, to: to, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List events in a calendar
     - GET /v1/calendars/{id}/events
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListCalendarEvents200Response> 
     */
    open class func listCalendarEventsWithRequestBuilder(id: UUID, from: Date? = nil, to: Date? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ListCalendarEvents200Response> {
        var localVariablePath = "/v1/calendars/{id}/events"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListCalendarEvents200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List calendar integrations
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListCalendarIntegrations200Response
     */
    open class func listCalendarIntegrations(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ListCalendarIntegrations200Response {
        return try await listCalendarIntegrationsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List calendar integrations
     - GET /v1/calendar-integrations
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListCalendarIntegrations200Response> 
     */
    open class func listCalendarIntegrationsWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ListCalendarIntegrations200Response> {
        let localVariablePath = "/v1/calendar-integrations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListCalendarIntegrations200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List calendar members
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListCalendarMembers200Response
     */
    open class func listCalendarMembers(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ListCalendarMembers200Response {
        return try await listCalendarMembersWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List calendar members
     - GET /v1/calendars/{id}/members
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListCalendarMembers200Response> 
     */
    open class func listCalendarMembersWithRequestBuilder(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ListCalendarMembers200Response> {
        var localVariablePath = "/v1/calendars/{id}/members"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListCalendarMembers200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List calendars
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListCalendars200Response
     */
    open class func listCalendars(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ListCalendars200Response {
        return try await listCalendarsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List calendars
     - GET /v1/calendars
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListCalendars200Response> 
     */
    open class func listCalendarsWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ListCalendars200Response> {
        let localVariablePath = "/v1/calendars"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListCalendars200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Remove a member from a calendar
     
     - parameter id: (path)  
     - parameter memberId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func removeCalendarMember(id: UUID, memberId: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await removeCalendarMemberWithRequestBuilder(id: id, memberId: memberId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Remove a member from a calendar
     - DELETE /v1/calendars/{id}/members/{memberId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter memberId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func removeCalendarMemberWithRequestBuilder(id: UUID, memberId: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/calendars/{id}/members/{memberId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let memberIdPreEscape = "\(APIHelper.mapValueToPathItem(memberId))"
        let memberIdPostEscape = memberIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{memberId}", with: memberIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Trigger sync for a calendar integration
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarIntegration
     */
    open class func syncCalendarIntegration(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarIntegration {
        return try await syncCalendarIntegrationWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Trigger sync for a calendar integration
     - POST /v1/calendar-integrations/{id}/sync
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarIntegration> 
     */
    open class func syncCalendarIntegrationWithRequestBuilder(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarIntegration> {
        var localVariablePath = "/v1/calendar-integrations/{id}/sync"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarIntegration>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update a calendar
     
     - parameter id: (path)  
     - parameter updateCalendarRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LockallyCalendar
     */
    open class func updateCalendar(id: UUID, updateCalendarRequest: UpdateCalendarRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> LockallyCalendar {
        return try await updateCalendarWithRequestBuilder(id: id, updateCalendarRequest: updateCalendarRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update a calendar
     - PATCH /v1/calendars/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter updateCalendarRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LockallyCalendar> 
     */
    open class func updateCalendarWithRequestBuilder(id: UUID, updateCalendarRequest: UpdateCalendarRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<LockallyCalendar> {
        var localVariablePath = "/v1/calendars/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCalendarRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LockallyCalendar>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update a calendar event
     
     - parameter id: (path)  
     - parameter eventId: (path)  
     - parameter updateCalendarEventRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarEvent
     */
    open class func updateCalendarEvent(id: UUID, eventId: UUID, updateCalendarEventRequest: UpdateCalendarEventRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarEvent {
        return try await updateCalendarEventWithRequestBuilder(id: id, eventId: eventId, updateCalendarEventRequest: updateCalendarEventRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update a calendar event
     - PATCH /v1/calendars/{id}/events/{eventId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter eventId: (path)  
     - parameter updateCalendarEventRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarEvent> 
     */
    open class func updateCalendarEventWithRequestBuilder(id: UUID, eventId: UUID, updateCalendarEventRequest: UpdateCalendarEventRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarEvent> {
        var localVariablePath = "/v1/calendars/{id}/events/{eventId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCalendarEventRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarEvent>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update a calendar integration
     
     - parameter id: (path)  
     - parameter updateCalendarIntegrationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarIntegration
     */
    open class func updateCalendarIntegration(id: UUID, updateCalendarIntegrationRequest: UpdateCalendarIntegrationRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarIntegration {
        return try await updateCalendarIntegrationWithRequestBuilder(id: id, updateCalendarIntegrationRequest: updateCalendarIntegrationRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update a calendar integration
     - PATCH /v1/calendar-integrations/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter updateCalendarIntegrationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarIntegration> 
     */
    open class func updateCalendarIntegrationWithRequestBuilder(id: UUID, updateCalendarIntegrationRequest: UpdateCalendarIntegrationRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarIntegration> {
        var localVariablePath = "/v1/calendar-integrations/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCalendarIntegrationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarIntegration>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update a calendar member's role
     
     - parameter id: (path)  
     - parameter memberId: (path)  
     - parameter updateCalendarMemberRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarMember
     */
    open class func updateCalendarMember(id: UUID, memberId: UUID, updateCalendarMemberRequest: UpdateCalendarMemberRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarMember {
        return try await updateCalendarMemberWithRequestBuilder(id: id, memberId: memberId, updateCalendarMemberRequest: updateCalendarMemberRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update a calendar member's role
     - PATCH /v1/calendars/{id}/members/{memberId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter memberId: (path)  
     - parameter updateCalendarMemberRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarMember> 
     */
    open class func updateCalendarMemberWithRequestBuilder(id: UUID, memberId: UUID, updateCalendarMemberRequest: UpdateCalendarMemberRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarMember> {
        var localVariablePath = "/v1/calendars/{id}/members/{memberId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let memberIdPreEscape = "\(APIHelper.mapValueToPathItem(memberId))"
        let memberIdPostEscape = memberIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{memberId}", with: memberIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCalendarMemberRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarMember>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update calendar policies
     
     - parameter updateCalendarPoliciesRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CalendarPolicies
     */
    open class func updateCalendarPolicies(updateCalendarPoliciesRequest: UpdateCalendarPoliciesRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CalendarPolicies {
        return try await updateCalendarPoliciesWithRequestBuilder(updateCalendarPoliciesRequest: updateCalendarPoliciesRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update calendar policies
     - PATCH /v1/calendar-policies
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter updateCalendarPoliciesRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CalendarPolicies> 
     */
    open class func updateCalendarPoliciesWithRequestBuilder(updateCalendarPoliciesRequest: UpdateCalendarPoliciesRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CalendarPolicies> {
        let localVariablePath = "/v1/calendar-policies"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCalendarPoliciesRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CalendarPolicies>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
