//
// DistributionListsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DistributionListsAPI {

    /**
     Create a distribution list
     
     - parameter createDistributionListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DistributionListDetail
     */
    open class func createDistributionList(createDistributionListRequest: CreateDistributionListRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> DistributionListDetail {
        return try await createDistributionListWithRequestBuilder(createDistributionListRequest: createDistributionListRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a distribution list
     - POST /v1/distribution-lists
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createDistributionListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DistributionListDetail> 
     */
    open class func createDistributionListWithRequestBuilder(createDistributionListRequest: CreateDistributionListRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<DistributionListDetail> {
        let localVariablePath = "/v1/distribution-lists"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createDistributionListRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DistributionListDetail>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a distribution list
     
     - parameter address: (path) Distribution list email address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteDistributionList(address: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteDistributionListWithRequestBuilder(address: address, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a distribution list
     - DELETE /v1/distribution-lists/{address}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter address: (path) Distribution list email address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteDistributionListWithRequestBuilder(address: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/distribution-lists/{address}"
        let addressPreEscape = "\(APIHelper.mapValueToPathItem(address))"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a distribution list
     
     - parameter address: (path) Distribution list email address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DistributionListDetail
     */
    open class func getDistributionList(address: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> DistributionListDetail {
        return try await getDistributionListWithRequestBuilder(address: address, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a distribution list
     - GET /v1/distribution-lists/{address}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter address: (path) Distribution list email address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DistributionListDetail> 
     */
    open class func getDistributionListWithRequestBuilder(address: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<DistributionListDetail> {
        var localVariablePath = "/v1/distribution-lists/{address}"
        let addressPreEscape = "\(APIHelper.mapValueToPathItem(address))"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DistributionListDetail>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List distribution lists
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListDistributionLists200Response
     */
    open class func listDistributionLists(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ListDistributionLists200Response {
        return try await listDistributionListsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List distribution lists
     - GET /v1/distribution-lists
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListDistributionLists200Response> 
     */
    open class func listDistributionListsWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ListDistributionLists200Response> {
        let localVariablePath = "/v1/distribution-lists"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListDistributionLists200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Replace distribution list members
     
     - parameter address: (path) Distribution list email address 
     - parameter replaceDistributionListMembersRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ReplaceDistributionListMembers200Response
     */
    open class func replaceDistributionListMembers(address: String, replaceDistributionListMembersRequest: ReplaceDistributionListMembersRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ReplaceDistributionListMembers200Response {
        return try await replaceDistributionListMembersWithRequestBuilder(address: address, replaceDistributionListMembersRequest: replaceDistributionListMembersRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Replace distribution list members
     - PUT /v1/distribution-lists/{address}/members
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter address: (path) Distribution list email address 
     - parameter replaceDistributionListMembersRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ReplaceDistributionListMembers200Response> 
     */
    open class func replaceDistributionListMembersWithRequestBuilder(address: String, replaceDistributionListMembersRequest: ReplaceDistributionListMembersRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ReplaceDistributionListMembers200Response> {
        var localVariablePath = "/v1/distribution-lists/{address}/members"
        let addressPreEscape = "\(APIHelper.mapValueToPathItem(address))"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: replaceDistributionListMembersRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReplaceDistributionListMembers200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
