//
// DraftsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DraftsAPI {

    /**
     Approve a pending draft (human)
     
     - parameter draftID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1DraftsDraftIDApprovePost(draftID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1DraftsDraftIDApprovePostWithRequestBuilder(draftID: draftID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Approve a pending draft (human)
     - POST /v1/drafts/{draftID}/approve
     - Sends the draft exactly as reviewed, through the agent stream (loop detector included). Fires draft.approved.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter draftID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1DraftsDraftIDApprovePostWithRequestBuilder(draftID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/drafts/{draftID}/approve"
        let draftIDPreEscape = "\(APIHelper.mapValueToPathItem(draftID))"
        let draftIDPostEscape = draftIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{draftID}", with: draftIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Withdraw a pending draft
     
     - parameter draftID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1DraftsDraftIDCancelPost(draftID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1DraftsDraftIDCancelPostWithRequestBuilder(draftID: draftID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Withdraw a pending draft
     - POST /v1/drafts/{draftID}/cancel
     - Only the API key that created the draft may cancel it.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter draftID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1DraftsDraftIDCancelPostWithRequestBuilder(draftID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/drafts/{draftID}/cancel"
        let draftIDPreEscape = "\(APIHelper.mapValueToPathItem(draftID))"
        let draftIDPostEscape = draftIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{draftID}", with: draftIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a draft
     
     - parameter draftID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1DraftsDraftIDGet(draftID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1DraftsDraftIDGetWithRequestBuilder(draftID: draftID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a draft
     - GET /v1/drafts/{draftID}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter draftID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1DraftsDraftIDGetWithRequestBuilder(draftID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/drafts/{draftID}"
        let draftIDPreEscape = "\(APIHelper.mapValueToPathItem(draftID))"
        let draftIDPostEscape = draftIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{draftID}", with: draftIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Reject a pending draft (human)
     
     - parameter draftID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1DraftsDraftIDRejectPost(draftID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1DraftsDraftIDRejectPostWithRequestBuilder(draftID: draftID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reject a pending draft (human)
     - POST /v1/drafts/{draftID}/reject
     - Body: {\"reason\": \"...\"} (optional). Fires draft.rejected.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter draftID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1DraftsDraftIDRejectPostWithRequestBuilder(draftID: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/drafts/{draftID}/reject"
        let draftIDPreEscape = "\(APIHelper.mapValueToPathItem(draftID))"
        let draftIDPostEscape = draftIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{draftID}", with: draftIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List drafts
     
     - parameter status: (query)  (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1DraftsGet(status: String? = nil, limit: Int? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1DraftsGetWithRequestBuilder(status: status, limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List drafts
     - GET /v1/drafts
     - Filter with ?status=pending_approval|sent|rejected|cancelled. Keys see drafts of granted mailboxes; admin sessions see all.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter status: (query)  (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1DraftsGetWithRequestBuilder(status: String? = nil, limit: Int? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        let localVariablePath = "/v1/drafts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Propose a new conversation as a draft
     
     - parameter mailbox: (path)  
     - parameter idempotencyKey: (header)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1InboxesMailboxDraftsPost(mailbox: String, idempotencyKey: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1InboxesMailboxDraftsPostWithRequestBuilder(mailbox: mailbox, idempotencyKey: idempotencyKey, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Propose a new conversation as a draft
     - POST /v1/inboxes/{mailbox}/drafts
     - New-conversation drafts ALWAYS require human approval (policy flag new_thread). Idempotency-Key required.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter mailbox: (path)  
     - parameter idempotencyKey: (header)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1InboxesMailboxDraftsPostWithRequestBuilder(mailbox: String, idempotencyKey: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/inboxes/{mailbox}/drafts"
        let mailboxPreEscape = "\(APIHelper.mapValueToPathItem(mailbox))"
        let mailboxPostEscape = mailboxPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{mailbox}", with: mailboxPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Idempotency-Key": idempotencyKey.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Propose a reply as a draft
     
     - parameter threadID: (path)  
     - parameter idempotencyKey: (header)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func v1ThreadsThreadIDDraftsPost(threadID: UUID, idempotencyKey: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await v1ThreadsThreadIDDraftsPostWithRequestBuilder(threadID: threadID, idempotencyKey: idempotencyKey, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Propose a reply as a draft
     - POST /v1/threads/{threadID}/drafts
     - The safe default over /reply: the deterministic policy engine auto-sends clean in-thread replies and holds anything risky (PII, new recipients, injection-flagged threads, always-approve mailboxes) for human approval. Fires draft.pending_approval when held. Idempotency-Key required.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter threadID: (path)  
     - parameter idempotencyKey: (header)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func v1ThreadsThreadIDDraftsPostWithRequestBuilder(threadID: UUID, idempotencyKey: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/threads/{threadID}/drafts"
        let threadIDPreEscape = "\(APIHelper.mapValueToPathItem(threadID))"
        let threadIDPostEscape = threadIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{threadID}", with: threadIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Idempotency-Key": idempotencyKey.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
