//
// EncryptionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class EncryptionAPI {

    /**
     Batch-lookup public keys by email
     
     - parameter emails: (query) Comma-separated list of email addresses 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BatchLookupPublicKeys200Response
     */
    open class func batchLookupPublicKeys(emails: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> BatchLookupPublicKeys200Response {
        return try await batchLookupPublicKeysWithRequestBuilder(emails: emails, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Batch-lookup public keys by email
     - GET /v1/encryption/keys/lookup
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter emails: (query) Comma-separated list of email addresses 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BatchLookupPublicKeys200Response> 
     */
    open class func batchLookupPublicKeysWithRequestBuilder(emails: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<BatchLookupPublicKeys200Response> {
        let localVariablePath = "/v1/encryption/keys/lookup"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "emails": (wrappedValue: emails.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BatchLookupPublicKeys200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Upload an encryption key pair
     
     - parameter createEncryptionKeyRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateEncryptionKey201Response
     */
    open class func createEncryptionKey(createEncryptionKeyRequest: CreateEncryptionKeyRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> CreateEncryptionKey201Response {
        return try await createEncryptionKeyWithRequestBuilder(createEncryptionKeyRequest: createEncryptionKeyRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Upload an encryption key pair
     - POST /v1/encryption/keys
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createEncryptionKeyRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateEncryptionKey201Response> 
     */
    open class func createEncryptionKeyWithRequestBuilder(createEncryptionKeyRequest: CreateEncryptionKeyRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<CreateEncryptionKey201Response> {
        let localVariablePath = "/v1/encryption/keys"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createEncryptionKeyRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateEncryptionKey201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Store an encryption recovery blob
     
     - parameter createEncryptionRecoveryRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func createEncryptionRecovery(createEncryptionRecoveryRequest: CreateEncryptionRecoveryRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await createEncryptionRecoveryWithRequestBuilder(createEncryptionRecoveryRequest: createEncryptionRecoveryRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Store an encryption recovery blob
     - POST /v1/encryption/recovery
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createEncryptionRecoveryRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func createEncryptionRecoveryWithRequestBuilder(createEncryptionRecoveryRequest: CreateEncryptionRecoveryRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/v1/encryption/recovery"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createEncryptionRecoveryRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get encryption key for a mailbox
     
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetEncryptionKey200Response
     */
    open class func getEncryptionKey(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> GetEncryptionKey200Response {
        return try await getEncryptionKeyWithRequestBuilder(email: email, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get encryption key for a mailbox
     - GET /v1/encryption/keys/{email}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetEncryptionKey200Response> 
     */
    open class func getEncryptionKeyWithRequestBuilder(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<GetEncryptionKey200Response> {
        var localVariablePath = "/v1/encryption/keys/{email}"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetEncryptionKey200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Rotate an encryption key
     
     - parameter rotateEncryptionKeyRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func rotateEncryptionKey(rotateEncryptionKeyRequest: RotateEncryptionKeyRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await rotateEncryptionKeyWithRequestBuilder(rotateEncryptionKeyRequest: rotateEncryptionKeyRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Rotate an encryption key
     - POST /v1/encryption/keys/rotate
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter rotateEncryptionKeyRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func rotateEncryptionKeyWithRequestBuilder(rotateEncryptionKeyRequest: RotateEncryptionKeyRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/v1/encryption/keys/rotate"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: rotateEncryptionKeyRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
