//
// IpPoolsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class IpPoolsAPI {

    /**
     Request a dedicated IP
     
     - parameter createDedicatedIPRequestRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DedicatedIPRequest
     */
    open class func createDedicatedIPRequest(createDedicatedIPRequestRequest: CreateDedicatedIPRequestRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> DedicatedIPRequest {
        return try await createDedicatedIPRequestWithRequestBuilder(createDedicatedIPRequestRequest: createDedicatedIPRequestRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Request a dedicated IP
     - POST /v1/dedicated-ip-requests
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createDedicatedIPRequestRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DedicatedIPRequest> 
     */
    open class func createDedicatedIPRequestWithRequestBuilder(createDedicatedIPRequestRequest: CreateDedicatedIPRequestRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<DedicatedIPRequest> {
        let localVariablePath = "/v1/dedicated-ip-requests"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createDedicatedIPRequestRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DedicatedIPRequest>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get current IP assignment
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetIPAssignment200Response
     */
    open class func getIPAssignment(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> GetIPAssignment200Response {
        return try await getIPAssignmentWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get current IP assignment
     - GET /v1/ip-assignment
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetIPAssignment200Response> 
     */
    open class func getIPAssignmentWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<GetIPAssignment200Response> {
        let localVariablePath = "/v1/ip-assignment"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetIPAssignment200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List dedicated IP requests
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListDedicatedIPRequests200Response
     */
    open class func listDedicatedIPRequests(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ListDedicatedIPRequests200Response {
        return try await listDedicatedIPRequestsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List dedicated IP requests
     - GET /v1/dedicated-ip-requests
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListDedicatedIPRequests200Response> 
     */
    open class func listDedicatedIPRequestsWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ListDedicatedIPRequests200Response> {
        let localVariablePath = "/v1/dedicated-ip-requests"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListDedicatedIPRequests200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
