//
// MailboxesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MailboxesAPI {

    /**
     Add a shared mailbox member
     
     - parameter email: (path)  
     - parameter addSharedMemberRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SharedMember
     */
    open class func addSharedMember(email: String, addSharedMemberRequest: AddSharedMemberRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> SharedMember {
        return try await addSharedMemberWithRequestBuilder(email: email, addSharedMemberRequest: addSharedMemberRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add a shared mailbox member
     - POST /v1/mailboxes/{email}/members
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter addSharedMemberRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SharedMember> 
     */
    open class func addSharedMemberWithRequestBuilder(email: String, addSharedMemberRequest: AddSharedMemberRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<SharedMember> {
        var localVariablePath = "/v1/mailboxes/{email}/members"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addSharedMemberRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SharedMember>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List shared mailbox members
     
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListSharedMembers200Response
     */
    open class func listSharedMembers(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> ListSharedMembers200Response {
        return try await listSharedMembersWithRequestBuilder(email: email, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List shared mailbox members
     - GET /v1/mailboxes/{email}/members
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListSharedMembers200Response> 
     */
    open class func listSharedMembersWithRequestBuilder(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<ListSharedMembers200Response> {
        var localVariablePath = "/v1/mailboxes/{email}/members"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListSharedMembers200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Remove a shared mailbox member
     
     - parameter email: (path)  
     - parameter memberEmail: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func removeSharedMember(email: String, memberEmail: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await removeSharedMemberWithRequestBuilder(email: email, memberEmail: memberEmail, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Remove a shared mailbox member
     - DELETE /v1/mailboxes/{email}/members/{memberEmail}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter memberEmail: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func removeSharedMemberWithRequestBuilder(email: String, memberEmail: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/mailboxes/{email}/members/{memberEmail}"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let memberEmailPreEscape = "\(APIHelper.mapValueToPathItem(memberEmail))"
        let memberEmailPostEscape = memberEmailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{memberEmail}", with: memberEmailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Soft-delete a mailbox
     
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func v1MailboxesEmailDelete(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await v1MailboxesEmailDeleteWithRequestBuilder(email: email, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Soft-delete a mailbox
     - DELETE /v1/mailboxes/{email}
     - Sets `soft_deleted_at = now()` and `hard_delete_after = now() + 90d` per design D25. A background sweep (planned) will hard-delete after the window. The mailbox is also disabled immediately. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func v1MailboxesEmailDeleteWithRequestBuilder(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/mailboxes/{email}"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Download a previously-issued mailbox export
     
     - parameter email: (path)  
     - parameter token: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: URL
     */
    open class func v1MailboxesEmailExportDownloadGet(email: String, token: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> URL {
        return try await v1MailboxesEmailExportDownloadGetWithRequestBuilder(email: email, token: token, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Download a previously-issued mailbox export
     - GET /v1/mailboxes/{email}/export/download
     - Public endpoint (no Authorization header). Validates the one-shot token from the URL, marks it used, and streams an mbox file. Second GET with the same token returns 404 — tokens are single-use. 
     - parameter email: (path)  
     - parameter token: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<URL> 
     */
    open class func v1MailboxesEmailExportDownloadGetWithRequestBuilder(email: String, token: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<URL> {
        var localVariablePath = "/v1/mailboxes/{email}/export/download"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Request a mailbox export
     
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: V1MailboxesEmailExportPost201Response
     */
    open class func v1MailboxesEmailExportPost(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> V1MailboxesEmailExportPost201Response {
        return try await v1MailboxesEmailExportPostWithRequestBuilder(email: email, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Request a mailbox export
     - POST /v1/mailboxes/{email}/export
     - Issues a one-shot \"presigned\" download URL for the mailbox's content in mbox format. The URL works without an Authorization header — the token in the query string is the authz. TTL is 5 minutes; the token is consumed on first GET.  **v1 caveat:** the synthesized mbox only contains outbound mail (from `lockally.messages`). v2 swaps in Stalwart's export primitive for full inbox + folder structure + flags. The endpoint contract stays unchanged. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<V1MailboxesEmailExportPost201Response> 
     */
    open class func v1MailboxesEmailExportPostWithRequestBuilder(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<V1MailboxesEmailExportPost201Response> {
        var localVariablePath = "/v1/mailboxes/{email}/export"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1MailboxesEmailExportPost201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a mailbox
     
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Mailbox
     */
    open class func v1MailboxesEmailGet(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> Mailbox {
        return try await v1MailboxesEmailGetWithRequestBuilder(email: email, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a mailbox
     - GET /v1/mailboxes/{email}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Mailbox> 
     */
    open class func v1MailboxesEmailGetWithRequestBuilder(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Mailbox> {
        var localVariablePath = "/v1/mailboxes/{email}"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Mailbox>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update a mailbox
     
     - parameter email: (path)  
     - parameter v1MailboxesEmailPatchRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Mailbox
     */
    open class func v1MailboxesEmailPatch(email: String, v1MailboxesEmailPatchRequest: V1MailboxesEmailPatchRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> Mailbox {
        return try await v1MailboxesEmailPatchWithRequestBuilder(email: email, v1MailboxesEmailPatchRequest: v1MailboxesEmailPatchRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update a mailbox
     - PATCH /v1/mailboxes/{email}
     - Supply at least one of `password`, `quota_bytes`, `disabled`. Returns the updated mailbox. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter v1MailboxesEmailPatchRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Mailbox> 
     */
    open class func v1MailboxesEmailPatchWithRequestBuilder(email: String, v1MailboxesEmailPatchRequest: V1MailboxesEmailPatchRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Mailbox> {
        var localVariablePath = "/v1/mailboxes/{email}"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: v1MailboxesEmailPatchRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Mailbox>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Remove the vacation responder
     
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func v1MailboxesEmailVacationDelete(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await v1MailboxesEmailVacationDeleteWithRequestBuilder(email: email, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Remove the vacation responder
     - DELETE /v1/mailboxes/{email}/vacation
     - Idempotent — 204 whether or not a row existed.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func v1MailboxesEmailVacationDeleteWithRequestBuilder(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/mailboxes/{email}/vacation"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get the vacation responder
     
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: VacationResponder
     */
    open class func v1MailboxesEmailVacationGet(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> VacationResponder {
        return try await v1MailboxesEmailVacationGetWithRequestBuilder(email: email, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get the vacation responder
     - GET /v1/mailboxes/{email}/vacation
     - Returns the stored vacation rule or 404 if none is set.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<VacationResponder> 
     */
    open class func v1MailboxesEmailVacationGetWithRequestBuilder(email: String, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<VacationResponder> {
        var localVariablePath = "/v1/mailboxes/{email}/vacation"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VacationResponder>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Set the vacation responder
     
     - parameter email: (path)  
     - parameter v1MailboxesEmailVacationPutRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: VacationResponder
     */
    open class func v1MailboxesEmailVacationPut(email: String, v1MailboxesEmailVacationPutRequest: V1MailboxesEmailVacationPutRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> VacationResponder {
        return try await v1MailboxesEmailVacationPutWithRequestBuilder(email: email, v1MailboxesEmailVacationPutRequest: v1MailboxesEmailVacationPutRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Set the vacation responder
     - PUT /v1/mailboxes/{email}/vacation
     - Upsert — same endpoint creates or replaces the rule. Clears `synced_at`; the rule is staged on lockally until a sync worker pushes it to the mail server. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter email: (path)  
     - parameter v1MailboxesEmailVacationPutRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<VacationResponder> 
     */
    open class func v1MailboxesEmailVacationPutWithRequestBuilder(email: String, v1MailboxesEmailVacationPutRequest: V1MailboxesEmailVacationPutRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<VacationResponder> {
        var localVariablePath = "/v1/mailboxes/{email}/vacation"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: v1MailboxesEmailVacationPutRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VacationResponder>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List mailboxes
     
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: V1MailboxesGet200Response
     */
    open class func v1MailboxesGet(limit: Int? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> V1MailboxesGet200Response {
        return try await v1MailboxesGetWithRequestBuilder(limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List mailboxes
     - GET /v1/mailboxes
     - Returns mailboxes under the calling tenant — active and soft-deleted. `?limit=N` between 1 and 200 (default 50). 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<V1MailboxesGet200Response> 
     */
    open class func v1MailboxesGetWithRequestBuilder(limit: Int? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<V1MailboxesGet200Response> {
        let localVariablePath = "/v1/mailboxes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1MailboxesGet200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create a mailbox
     
     - parameter v1MailboxesPostRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Mailbox
     */
    open class func v1MailboxesPost(v1MailboxesPostRequest: V1MailboxesPostRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> Mailbox {
        return try await v1MailboxesPostWithRequestBuilder(v1MailboxesPostRequest: v1MailboxesPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a mailbox
     - POST /v1/mailboxes
     - Creates a mailbox on a tenant-verified domain. If `password` is omitted, lockally generates a 16-char password and returns it in the response — shown once.  **Gate.** The mailbox's domain must already be registered AND verified for this tenant (via `/v1/domains` + `/v1/domains/{domain}/verify`).  **Idempotent.** Re-posting the same email returns the existing mailbox UNTOUCHED — password is NOT regenerated. To change a password, use PATCH instead. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter v1MailboxesPostRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Mailbox> 
     */
    open class func v1MailboxesPostWithRequestBuilder(v1MailboxesPostRequest: V1MailboxesPostRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Mailbox> {
        let localVariablePath = "/v1/mailboxes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: v1MailboxesPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Mailbox>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List all vacation responders
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: V1VacationGet200Response
     */
    open class func v1VacationGet(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> V1VacationGet200Response {
        return try await v1VacationGetWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all vacation responders
     - GET /v1/vacation
     - Returns every vacation responder for the calling tenant.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<V1VacationGet200Response> 
     */
    open class func v1VacationGetWithRequestBuilder(apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<V1VacationGet200Response> {
        let localVariablePath = "/v1/vacation"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1VacationGet200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
