//
// SendAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SendAPI {

    /**
     * enum for parameter status
     */
    public enum Status_v1MessagesGet: String, Sendable, CaseIterable {
        case queued = "queued"
        case sending = "sending"
        case delivered = "delivered"
        case bounced = "bounced"
        case deferred = "deferred"
        case complaint = "complaint"
    }

    /**
     List outbound messages
     
     - parameter status: (query)  (optional)
     - parameter sender: (query) Exact match against the &#x60;from&#x60; mailbox. (optional)
     - parameter q: (query) Free-text search across subject + sender. (optional)
     - parameter since: (query) Only messages queued at or after this RFC 3339 instant. (optional)
     - parameter cursor: (query) queued_at of the prior page boundary. Pass back the &#x60;next_cursor&#x60; returned by the previous call. (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: V1MessagesGet200Response
     */
    open class func v1MessagesGet(status: Status_v1MessagesGet? = nil, sender: String? = nil, q: String? = nil, since: Date? = nil, cursor: String? = nil, limit: Int? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> V1MessagesGet200Response {
        return try await v1MessagesGetWithRequestBuilder(status: status, sender: sender, q: q, since: since, cursor: cursor, limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List outbound messages
     - GET /v1/messages
     - Returns recent outbound messages for the calling tenant, sorted newest first. Backs the send-status pill in the SvelteKit /sends view and the outbound search box. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter status: (query)  (optional)
     - parameter sender: (query) Exact match against the &#x60;from&#x60; mailbox. (optional)
     - parameter q: (query) Free-text search across subject + sender. (optional)
     - parameter since: (query) Only messages queued at or after this RFC 3339 instant. (optional)
     - parameter cursor: (query) queued_at of the prior page boundary. Pass back the &#x60;next_cursor&#x60; returned by the previous call. (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<V1MessagesGet200Response> 
     */
    open class func v1MessagesGetWithRequestBuilder(status: Status_v1MessagesGet? = nil, sender: String? = nil, q: String? = nil, since: Date? = nil, cursor: String? = nil, limit: Int? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<V1MessagesGet200Response> {
        let localVariablePath = "/v1/messages"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sender": (wrappedValue: sender?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "q": (wrappedValue: q?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "since": (wrappedValue: since?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "cursor": (wrappedValue: cursor?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1MessagesGet200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Cancel a scheduled send
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func v1MessagesIdDelete(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await v1MessagesIdDeleteWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Cancel a scheduled send
     - DELETE /v1/messages/{id}
     - Cancels a still-scheduled message (future queued_at). Already sending/sent → 409.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func v1MessagesIdDeleteWithRequestBuilder(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/messages/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get message status
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MessageDetail
     */
    open class func v1MessagesIdGet(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> MessageDetail {
        return try await v1MessagesIdGetWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get message status
     - GET /v1/messages/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MessageDetail> 
     */
    open class func v1MessagesIdGetWithRequestBuilder(id: UUID, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<MessageDetail> {
        var localVariablePath = "/v1/messages/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageDetail>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Aggregate delivery stats
     
     - parameter from: (query) Window start (default 7 days ago). (optional)
     - parameter to: (query) Window end (default now). (optional)
     - parameter domain: (query) Filter by sender domain. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MessageStats
     */
    open class func v1MessagesStatsGet(from: Date? = nil, to: Date? = nil, domain: String? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> MessageStats {
        return try await v1MessagesStatsGetWithRequestBuilder(from: from, to: to, domain: domain, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Aggregate delivery stats
     - GET /v1/messages/stats
     - Counts by delivery outcome (delivered/bounced/deferred/complaint) plus rates over a window, from the delivery-event store. Privacy-first: this reflects what receiving servers reported, NOT whether a human opened the mail — Lockally does no open/click tracking. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter from: (query) Window start (default 7 days ago). (optional)
     - parameter to: (query) Window end (default now). (optional)
     - parameter domain: (query) Filter by sender domain. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MessageStats> 
     */
    open class func v1MessagesStatsGetWithRequestBuilder(from: Date? = nil, to: Date? = nil, domain: String? = nil, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<MessageStats> {
        let localVariablePath = "/v1/messages/stats"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "domain": (wrappedValue: domain?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageStats>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Send a batch of emails
     
     - parameter idempotencyKey: (header)  
     - parameter v1SendBatchPostRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: V1SendBatchPost200Response
     */
    open class func v1SendBatchPost(idempotencyKey: String, v1SendBatchPostRequest: V1SendBatchPostRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> V1SendBatchPost200Response {
        return try await v1SendBatchPostWithRequestBuilder(idempotencyKey: idempotencyKey, v1SendBatchPostRequest: v1SendBatchPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Send a batch of emails
     - POST /v1/send/batch
     - Sends up to 500 messages in one call. Each is validated and enqueued independently — a bad message fails only its own slot (partial success, HTTP 200). One `Idempotency-Key` header covers the batch; per-message keys are derived as `<key>:<index>`. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter idempotencyKey: (header)  
     - parameter v1SendBatchPostRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<V1SendBatchPost200Response> 
     */
    open class func v1SendBatchPostWithRequestBuilder(idempotencyKey: String, v1SendBatchPostRequest: V1SendBatchPostRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<V1SendBatchPost200Response> {
        let localVariablePath = "/v1/send/batch"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: v1SendBatchPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1SendBatchPost200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Send an email
     
     - parameter idempotencyKey: (header)  
     - parameter v1SendPostRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: V1SendPost202Response
     */
    open class func v1SendPost(idempotencyKey: String, v1SendPostRequest: V1SendPostRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> V1SendPost202Response {
        return try await v1SendPostWithRequestBuilder(idempotencyKey: idempotencyKey, v1SendPostRequest: v1SendPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Send an email
     - POST /v1/send
     - Submits an email for delivery via lockally. Returns 202 immediately once the message is accepted into lockally's queue; the actual SMTP submission to the recipient is async. Track delivery via `GET /v1/messages/{id}` or webhook subscriptions for `delivery.delivered` / `delivery.bounced` / `delivery.complaint`.  **Idempotency-Key required.** Per design L7 — any unique string per send, 24-hour dedupe window. Repeated calls with the same key return byte-exact the original response and do NOT create a duplicate message.  **Sender authorisation.** `from` must be a non-disabled mailbox owned by the calling tenant on a verified domain. Sending from aliases is not yet supported.  **Rate cap.** Per-tenant `rate_cap_per_min` (returned on `/v1/tenant`) is enforced — 429 with `Retry-After: 60` once tripped.  **Recipient warning.** Over 25 total recipients (To+Cc+Bcc) sets a `warning` field in the response — large fan-outs queue noticeably at scale. Hard cap is 100/send. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - responseHeaders: [Idempotent-Replay(String)]
     - parameter idempotencyKey: (header)  
     - parameter v1SendPostRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<V1SendPost202Response> 
     */
    open class func v1SendPostWithRequestBuilder(idempotencyKey: String, v1SendPostRequest: V1SendPostRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<V1SendPost202Response> {
        let localVariablePath = "/v1/send"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: v1SendPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1SendPost202Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
