//
// SignupAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SignupAPI {

    /**
     Sign up a new tenant
     
     - parameter signupRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: V1AdminLoginPost200Response
     */
    open class func signup(signupRequest: SignupRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) async throws(ErrorResponse) -> V1AdminLoginPost200Response {
        return try await signupWithRequestBuilder(signupRequest: signupRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Sign up a new tenant
     - POST /v1/signup
     - parameter signupRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<V1AdminLoginPost200Response> 
     */
    open class func signupWithRequestBuilder(signupRequest: SignupRequest, apiConfiguration: LockallyAPIConfiguration = LockallyAPIConfiguration.shared) -> RequestBuilder<V1AdminLoginPost200Response> {
        let localVariablePath = "/v1/signup"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: signupRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<V1AdminLoginPost200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
